cmu-delphi/delphi-epidata

src/acquisition/wiki/create_wiki_raw_table.sql
add SQL command to modify the maximum length of varchar because we need to extract more articles now
=> add sql command to modify the maximum length of data column

src/acquisition/wiki/wiki_extract.py
fix a bug for non-ascii character. The mysql is old-version on the server, so the encoding method is wrong.
=> fix a bug for non-ascii character

src/acquisition/wiki/wiki_extract.py
First encode the word as utf-8, then decode as latin-1, which makes it consistent with the server-side encoding mechanism
=> a more elegant way to solve encoding problem for non-ascii character

src/acquisition/norostat/norostat_raw.py
Around December 2018, the NoroSTAT data-table page was updated and the old span
describing the modification date was removed. The norostat_update script expects
to be able to extract information from this tag and fails when it is not
present. Luckily, there is currently a meta tag (perhaps added to replace the
span) that serves the same purpose. Check for both types of elements to try to
extract the dateModified. (Prioritize the meta tag over the span.) (This change
should fix the error currently encountered by the norostat_update script.)
=> Fix norostat_update: use dateModified from meta tag (span is gone)

docs/README.md
=> testing, ignore

src/server/api.php
- a **huge** thanks to Pedrito Maynard-Zhang (pedritom@amazon.com) for 
disclosing this vulnerability
- PoC confirms SQL injection at the wiki endpoint
- vulnerability is fixed by this change
=> sanitize user input

integrations/server/test_covidcast_meta.py, src/server/api.php
- adds mean and stdev to the covidcast_meta endpoint
- ✔ All 11 tests passed!
=> covidcast_meta mean and stdev

src/client/delphi_epidata.R, src/client/delphi_epidata.coffee, src/client/delphi_epidata.js, src/client/delphi_epidata.py, src/client/packaging/pypi/README.md
testing: all unit and integration tests pass.
=> update endpoint to delphi.cmu.edu

deploy.json, integrations/acquisition/covidcast/test_csv_uploading.py, src/acquisition/covidcast/csv_importer.py, src/acquisition/covidcast/csv_to_database.py, src/acquisition/covidcast/data_dir_readme.md, src/acquisition/covidcast/database.py, src/acquisition/covidcast/file_archiver.py, tests/acquisition/covidcast/test_csv_importer.py, tests/acquisition/covidcast/test_csv_to_database.py, tests/acquisition/covidcast/test_database.py, tests/acquisition/covidcast/test_file_archiver.py
- the full implementation is split into multiple smaller commits for easier review
- should be trivial to automate once deployed
=> covidcast acquisition

src/acquisition/covidcast/csv_to_database.py
- the **_single_** untested line in all of `acquisition/covidcast/` had 
a bug... /facepalm
=> actually parse arguments

src/acquisition/covidcast/direction.py, tests/acquisition/covidcast/test_direction.py
- just introducing a helper class, which is not used yet
- tests included, 100% coverage
=> covidcast direction calculation

integrations/acquisition/covidcast/test_csv_uploading.py, integrations/client/test_delphi_epidata.py, integrations/server/test_covidcast.py, integrations/server/test_covidcast_meta.py, src/acquisition/covidcast/csv_importer.py, src/acquisition/covidcast/csv_to_database.py, src/acquisition/covidcast/database.py, src/acquisition/covidcast/direction.py, src/ddl/covidcast.sql, src/server/api.php, tests/acquisition/covidcast/test_csv_importer.py, tests/acquisition/covidcast/test_csv_to_database.py, tests/acquisition/covidcast/test_database.py, tests/acquisition/covidcast/test_direction.py
see individual commits for details
=> add timestamps, no more direction column

integrations/acquisition/covidcast/test_direction_updating.py, src/acquisition/covidcast/direction_updater.py, tests/acquisition/covidcast/test_direction_updater.py
- updates direction for all _daily_ covidcast rows
- new unit and integration tests
- all new and existing tests pass
=> covidcast automatic direction updater

integrations/acquisition/covidcast/test_direction_updating.py, src/acquisition/covidcast/database.py, src/acquisition/covidcast/direction.py, src/acquisition/covidcast/direction_updater.py, tests/acquisition/covidcast/test_direction_updater.py
avoid quadratic time at the database by scanning entire time-series in linear time in python
=> faster direction for covidcast

src/acquisition/covidcast/direction.py
- work in progress
- no additional testing as this is needed for validation asap
- unit and integrations tests pass
- i owe unit tests (and much more) for this
=> threshold direction at 20% of chart stdev

src/acquisition/covidcast/database.py, src/acquisition/covidcast/direction.py, src/acquisition/covidcast/direction_updater.py, src/ddl/covidcast.sql
- no new tests
- unit and integration tests pass
- i owe (even more) tests...
=> slope threshold based on stdev across locations

src/acquisition/covidcast/direction_updater.py
- unit and integrations still pass...
- todo on me to add test case that would have caught this
=> fix a tiny bug

src/acquisition/covidcast/csv_importer.py
- unit and integration tests pass
- i owe *yet another* test
=> stop `nan` from breaking everything

src/acquisition/covidcast/csv_importer.py
=> better `nan` protection

src/acquisition/covidcast/direction.py
=> direction threshold 20% -> 10%

docs/api/README.md, docs/api/fluview_meta.md, integrations/server/test_fluview_meta.py, src/client/delphi_epidata.R, src/client/delphi_epidata.coffee, src/client/delphi_epidata.js, src/client/delphi_epidata.py, src/server/api.php
- re-use the existing code for the `fluview` bits of the `meta` endpoint
- updated all client libraries
- added new integration test
- wrote new doc and updated table of endpoints
- all unit and integration tests pass
=> add `fluview_meta` endpoint

src/client/packaging/pypi/delphi_epidata/__init__.py, src/client/packaging/pypi/setup.py
- install with `pip install delphi-epidata`
=> pypi 0.0.5 release of `delphi-epidata`

docs/api/covidcast.md, docs/api/covidcast_signals.md
Work in progress. I'm expanding the API documentation for the COVIDcast signals so consumers clearly understand the new signals and their meaning.
=> Expand the documentation of COVIDcast signals

docs/api/covidcast.md, docs/api/covidcast_signals.md
Additional documentation for the COVIDcast API.
=> Describe megacounties, combined sensor, Google drop, Quidel counties

docs/api/covidcast.md, docs/api/covidcast_signals.md
Reverts cmu-delphi/delphi-epidata#105 until released
=> Revert "Describe megacounties, combined sensor, Google drop, Quidel counties"

docs/api/covidcast_signals.md
Adds signal names and descriptions for both new community signals from fb-survey
=> Add Facebook community signals

docs/api/covidcast_signals.md
Fix wording. Hopefully I caught everything.
=> We report percentages, not fractions

docs/api/covidcast.md, docs/api/covidcast_changelog.md, docs/api/covidcast_signals.md
A slightly expanded introduction and links to our mailing list.
=> Make COVIDcast docs more welcoming and link to mailing list

docs/api/covidcast-signals/doctor-visits.md, docs/api/covidcast-signals/fb-survey.md, docs/api/covidcast-signals/google-survey.md, docs/api/covidcast-signals/hospital-admissions.md, docs/api/covidcast-signals/jhu-csse.md, docs/api/covidcast-signals/safegraph.md, docs/api/covidcast-signals/usa-facts.md, docs/api/covidcast_geography.md, docs/api/covidcast_signals.md
This documents Hospital Admissions and USAFacts, as well as making miscellaneous improvements to the other sources. Thanks to Jingjing and Maria for drafts of the source docs.
=> v1.4.1 COVIDcast API docs

docs/api/covidcast-signals/indicator-combination.md
Based on material from Pratik and Addison.
Dev preview: http://rosmarus.refsmmat.com/delphi-epidata/api/covidcast-signals/indicator-combination.html
=> First draft of combination indicator documentation

docs/api/covidcast-signals/google-survey.md
Based on text provided by Natalia and Justin.
=> First draft of detailed Google Survey documentation

src/acquisition/covidcast/data_dir_readme.md
* What causes failed CSV files
* How to add a new data source
=> Add more documentation to covidcast data directory

.github/workflows/ci.yaml
adds a github action with continuous testing of this repo.
setup is based on the development setup instructions.
=> github action for continious testing

src/server/.htaccess
Reverts cmu-delphi/delphi-epidata#171
Caused an internal server error on delphi.cmu.edu
=> Revert "Enable gzip/brotli compression and caching of API responses"

docs/api/covidcast-signals/doctor-visits.md, docs/api/covidcast-signals/fb-survey.md, docs/api/covidcast-signals/hospital-admissions.md, docs/api/covidcast-signals/quidel.md
Fixes cmu-delphi/covidcast-indicators#175
For these signals below:
- Quidel
- Doctor's Visits
- Hospital-Admission
- Symptom Surveys
=> Fixed errors in the documentation of standard error

docs/api/covidcast.md, docs/api/covidcast_clients.md, docs/api/covidcast_geography.md
- Make R example work with latest package version
- Make megacounty explanation clearer
- Advertise the clients a bit more
=> General documentation improvements

src/acquisition/covidcast/csv_importer.py, src/acquisition/covidcast/data_dir_readme.md, tests/acquisition/covidcast/test_csv_importer.py
This was remarkably straightforward?
API ingestion hookups to support cmu-delphi/covidcast-indicators#192
=> Support 'nation' as geo type with alpha values

integrations/acquisition/covidcast/test_csv_uploading.py, src/acquisition/covidcast/csv_importer.py, src/acquisition/covidcast/csv_to_database.py, src/acquisition/covidcast/file_archiver.py, tests/acquisition/covidcast/test_csv_to_database.py
still needs some tests and documentation, but this should do the trick
=> csv file loading with explicit 'issue' dates

dev/docker/database/epidata/Dockerfile, dev/docker/web/epidata/Dockerfile
=> grant read permissions in Dockerfiles to various internal libraries

docs/api/covidcast_signals.md
Use the from_claims variant for Hospital Admissions
=> Update map signals for 1.9.2

docs/api/covidcast-signals/jhu-csse.md, docs/api/covidcast_changelog.md
Geomapping refactoring of the indicators codebase have changed the meaning or calculation of some FIPS or State totals
* Fixes cmu-delphi/covidcast-indicators#217
* Fixes cmu-delphi/covidcast-indicators#236
=> mod changelog to incorporate JHU geocoding

docs/api/covidcast-signals/fb-survey.md, docs/symptom-survey/coding.md
Document the signals that are ready for public release.
=> Wave 4 survey signal documentation

src/acquisition/covidcast/csv_importer.py, tests/acquisition/covidcast/test_csv_importer.py
This adds an additional sanity check for infinite values in CSV data (which is not included in the isnan() check). This partially addresses issue #203 which contains an infinite value but did not fail validation at parse time.
=> Add sanity checks for +/-inf in CSV data.

integrations/client/test_delphi_epidata.py, src/client/delphi_epidata.R, src/client/delphi_epidata.coffee, src/client/delphi_epidata.js, src/client/delphi_epidata.py
=> add geo_values support in raw clients

integrations/client/test_delphi_epidata.py
- see commit comments for details
- fixes #251
=> fix failing integration test

docs/epidata_development.md, docs/new_endpoint_tutorial.md
- mainly adding documentation around bind-mounting local sources to prevent the need to rebuild images all the time
- also update some links
=> update dev guides

docs/api/covidcast-signals/doctor-visits.md
=> Document DV holiday effects

docs/api/covidcast-signals/safegraph.md, docs/api/covidcast_changelog.md
List geo changes to safegraph in changelog. Fixes cmu-delphi/covidcast-indicators#416
=> List geo changes to safegraph in changelog

docs/api/covidcast-signals/changehc.md
Maybe should be called Change Change signal name
=> Change signal name

docs/api/covidcast-signals/safegraph.md
Based on suggestions made in #302.
Please add comments and suggestions on language as you see fit and I will make the adjustments.
=> Safegraph patterns docs: Additions and Revisions

src/acquisition/covidcast/csv_importer.py, tests/acquisition/covidcast/test_csv_importer.py
Summary of changes:
- Add HHS support to csv importer.
Basically just followed [this commit](https://github.com/cmu-delphi/delphi-epidata/commit/7b51799557cbd2d5fcce337f9c49c0a87addfbf5) which added nation support.
@dfarrow0 since I can't add reviewers in this repo.
=> Add HHS support and tests

integrations/client/test_delphi_epidata.py, integrations/server/test_covidcast.py, src/client/delphi_epidata.py
See https://github.com/cmu-delphi/covidcast/issues/362. I've verified that the post works on the server, but that was just a single query and not what the best way to do more intensive stuff is.
=> Change requests from GET to POST

docs/api/covidcast-signals/fb-survey.md
See https://github.com/cmu-delphi/covidcast-indicators/issues/601
=> Document upcoming survey signals

docs/api/README.md, docs/api/covid_hosp.md, docs/api/covidcast.md, docs/api/covidcast_meta.md, docs/api/delphi.md, docs/api/flusurv.md, docs/api/fluview.md, docs/api/fluview_clinical.md, docs/api/fluview_meta.md, docs/api/gft.md, docs/api/meta.md, docs/api/nidss_dengue.md, docs/api/nidss_flu.md, docs/api/nowcast.md, docs/api/sensors.md, docs/api/twitter.md, docs/api/wiki.md, docs/new_endpoint_tutorial.md, integrations/acquisition/covidcast/test_covidcast_meta_caching.py, integrations/server/test_api_analytics.py, integrations/server/test_covidcast.py, integrations/server/test_covidcast_meta.py, src/client/delphi_epidata.R, src/client/delphi_epidata.coffee, src/client/delphi_epidata.js, src/client/delphi_epidata.py, src/server/api.php, tests/server/dev_test_granular_sensor_authentication.py
=> feat: rename api parameter source -> endpoint

src/client/delphi_epidata.R, src/client/delphi_epidata.coffee, src/client/delphi_epidata.js
=> feat: support language parameter in wiki source

deploy.json
- update `deploy.json` with new package structure
=> covid hosp: deploy subpackages

docs/api/covidcast-signals/nchs-mortality.md
I wanted to explain how it's different from the other death data, so I stated that explicitly, and fixed a few formatting bugs.
=> Clarify and expand NCHS documentation

docs/api/covidcast_geography.md
Addresses #323 
Please let me know if there is more to this than I realized, thanks.
=> Add 'hhs' and 'nation' to geos described on covidcast_geography.md

docs/api/covid_hosp.md, docs/api/covid_hosp_facility.md, docs/api/covid_hosp_facility_lookup.md
- minor updates to the existing covid_hosp doc
- added covid_hosp_facility and covid_hosp_facility_lookup doc
=> add facility endpoints to api docs

docs/symptom-survey/coding.md
So future survey data analysts know when the change happened.
=> Explain that item V1 is now enabled

docs/api/README.md, docs/api/afhsb.md, docs/api/cdc.md, docs/api/delphi.md, docs/api/dengue_nowcast.md, docs/api/dengue_sensors.md, docs/api/ecdc_ili.md, docs/api/flusurv.md, docs/api/fluview.md, docs/api/fluview_clinical.md, docs/api/fluview_meta.md, docs/api/gft.md, docs/api/ght.md, docs/api/kcdc_ili.md, docs/api/meta.md, docs/api/meta_afhsb.md, docs/api/meta_norostat.md, docs/api/nidss_dengue.md, docs/api/nidss_flu.md, docs/api/norostat.md, docs/api/nowcast.md, docs/api/paho_dengue.md, docs/api/quidel.md, docs/api/sensors.md, docs/api/twitter.md, docs/api/wiki.md
Correcting README file:
Source to Endpoint as mentioned in #682
Still working through other docs.
=> API "Source" to "Endpoint"

integrations/acquisition/covidcast_nowcast/test_csv_uploading.py, integrations/client/test_delphi_epidata.py, integrations/server/test_covidcast_nowcast.py, src/acquisition/covidcast_nowcast/load_sensors.py, src/client/delphi_epidata.py, src/ddl/covidcast_nowcast.sql, src/server/api.php
Based off #355, only new commits are f3c84f2 and onward. Basically steals a bunch of the covidcast code for the PHP and uses a s lightly different table definition (which is still to be finalized).
TODO:
@krivard for review (let me know if theres anyone else I should tag)
cc: @mariajahja
=> Nowcast sensor endpoint

deploy.json
Forgot to do this and was causing deploy to fail.
@korlaxxalrok
=> add nowcast to deploy json

docs/api/covid_hosp_facility_lookup.md
=> Covid Hosp - Facility Lookup Placement

src/acquisition/covidcast/database.py
this is not the 'right way' to fix it, but it should be able to improve the timing of the computation in the meanwhile
(all tests pass)
=> micro-delta to relieve main pain point of metacache update performance.

integrations/acquisition/covidcast/test_csv_uploading.py, integrations/client/test_delphi_epidata.py, src/server/api.php, src/server/api_helpers.php
Reverts cmu-delphi/delphi-epidata#337, which was merged prematurely. We can re-apply those changes once the server is happily chugging along on PHP 7.
=> Revert "streaming support"

integrations/acquisition/covidcast_nowcast/test_csv_uploading.py, integrations/client/test_delphi_epidata.py, integrations/server/test_covidcast_nowcast.py, src/acquisition/covidcast_nowcast/load_sensors.py, src/client/delphi_epidata.py, src/ddl/covidcast_nowcast.sql, src/server/api.php, tests/acquisition/covidcast_nowcast/test_load_sensors.py
After discussing with @mariajahja on what fields we want to keep in this db, we decided to just add a single sensor name column to specify which source/signal/sensorization scheme we want to query for.
@krivard for review
=> Add sensor name column to nowcast db

src/acquisition/covid_hosp/state_daily/update.py
Make state daily use state daily database and network (instead of state timeseries database and network)
=> fix state daily import

docs/api/covidcast-signals/_source-template.md, docs/api/covidcast-signals/chng.md, docs/api/covidcast-signals/doctor-visits.md, docs/api/covidcast-signals/fb-survey.md, docs/api/covidcast-signals/ght.md, docs/api/covidcast-signals/google-survey.md, docs/api/covidcast-signals/google-symptoms.md, docs/api/covidcast-signals/hhs.md, docs/api/covidcast-signals/hospital-admissions.md, docs/api/covidcast-signals/indicator-combination.md, docs/api/covidcast-signals/jhu-csse.md, docs/api/covidcast-signals/nchs-mortality.md, docs/api/covidcast-signals/quidel.md, docs/api/covidcast-signals/safegraph.md, docs/api/covidcast-signals/usa-facts.md, docs/api/covidcast_licensing.md
Still todo: 
* limitations
* lag
* decide whether to include facilities signals or put them off to a future release cycle
I will be out from the 21st through the new year, so @chinandrew and @dfarrow0 will be picking up any remaining work on this PR.
=> API docs: initial add of HHS COVIDcast source

src/client/packaging/pypi/delphi_epidata/__init__.py, src/client/packaging/pypi/setup.py
=> Bump epidata version to 0.0.9

src/client/packaging/pypi/delphi_epidata/__init__.py, src/client/packaging/pypi/setup.py
setup and init; guess 0.0.9 went up back in December?
=> Bump epidata version up to 0.0.10

src/client/packaging/pypi/delphi_epidata/__init__.py, src/client/packaging/pypi/setup.py
=> Fix epidata requires and bump to 0.0.11

docs/api/covidcast-signals/fb-survey.md
My autoformatter went a little wild with removing end-of-line spaces, but the only substantive change is on line 336.
=> Document new V2 signal (# vaccine doses)

src/acquisition/covidcast/database.py, tests/acquisition/covidcast/test_database.py
Previously this always returned None
Improves #415
=> Retrieve the modified DB row count using cursor.rowcount

docs/symptom-survey/problems.md, docs/symptom-survey/survey-files.md
Any issues that affect interpretation of the data (or that data users might be surprised by).
=> Documentation page on survey problems

docs/api/covidcast-signals/fb-survey.md, docs/symptom-survey/coding.md
Item C14a replaces item C14 starting in Wave 8.
=> Add documentation for survey item C14a

src/server/api_helpers.php
=> Stop logging all queries as errors

docs/api/covidcast-signals/fb-survey.md
Add limitations, mention it's age 18+, link to dashboard.
=> Improve fb-survey documentation

docs/api/covidcast-signals/chng.md
=> Document that CHNG is available at nation geo-type

src/acquisition/covidcast/signal_dash_data_generator.py, src/ddl/signal_dashboard.sql, src/server/api.php, tests/acquisition/covidcast/test_signal_dash_data_generator.py
- Update coverage generation to count all geo_types
- Change DB schema to persist counts instead of individual geos
- Update API to return counts
- Update tests
- Also fix column format for persisted dates
Iterates on #438
=> Switch coverage to use counts

src/acquisition/covidcast/signal_dash_data_generator.py, src/server/api.php, tests/acquisition/covidcast/test_signal_dash_data_generator.py
- Also fixes a datetime->date bug.
- Also updates the API to return all the coverage data, nested.
Progress on #438
=> Switch to covidcast for signal dash

src/acquisition/covidcast/signal_dash_data_generator.py, tests/acquisition/covidcast/test_signal_dash_data_generator.py
Change dashboard coverage to look back over previous 28 days instead of just the most recent day. Update tests.
Improves #438
=> Update coverage to cover multiple days

src/acquisition/covidcast/signal_dash_data_generator.py, tests/acquisition/covidcast/test_signal_dash_data_generator.py
=> Remove old coverage from DB on write

src/acquisition/covidcast/signal_dash_data_generator.py
=> Properly update count when coverage changes

integrations/acquisition/covidcast/test_csv_uploading.py, integrations/client/test_delphi_epidata.py, src/server/_common.py, src/server/_config.py, src/server/_printer.py, src/server/main.py
=> [flask]: compatibility mode

docs/api/covidcast-signals/fb-survey.md
The schooling indicators seemed to fit best in the "Behavior" section, but perhaps would be better in a new section.
=> [fb-survey] Describe E2 schooling items

src/server/_printer.py, src/server/endpoints/covidcast.py, src/server/endpoints/covidcast_utils/__init__.py, src/server/endpoints/covidcast_utils/dates.py, tests/server/endpoints/covidcast_utils/test_dates.py
similar to covidcast-csv-server https://github.com/cmu-delphi/covidcast-csv-server.
as mentioned in the docs with the new streaming and custom endpoints we could add the csv server functionality into the flask api directly.
=> [flask] add /covidcast/csv endpoint

src/server/_printer.py
maybe otherwise the proxy is waiting till it "end" but there is never anything
=> [flask]: send something for empty csv files

src/server/_printer.py, src/server/endpoints/signal_dashboard_status.py
closes #497
not 100% sure whether it will fix it but it should avoid that an error is tried to be serialized
Moreover, tries to avoid this error by changing the logic the dashboard status is computed
=> possible error fixes

docs/api/covidcast-signals/indicator-combination.md, docs/api/covidcast-signals/safegraph-inactive.md, docs/api/covidcast-signals/safegraph.md, docs/api/covidcast_changelog.md
=> Docs update: move safegraph to inactive category

deploy.json
fixes the following deployment error on midas:
```
failed to deploy cmu-delphi/delphi-epidata (sgratzl/flaskx) No module named 'delphi.epidata.server.endpoints'
```
=> Add Flask server files to correct deployment location

deploy.json
based on https://github.com/cmu-delphi/github-deploy-repo/blob/main/src/actions/copymove.py
=> build: try to fix moving tests

.github/workflows/ci.yaml
=> [flask] separate image step and only build on certain branches

.github/workflows/ci.yaml
to avoid creating faulty images
=> ci: require build to be successful before creating image

integrations/server/test_covidcast.py, integrations/server/test_covidcast_endpoints.py
Fixed a few tests in the merge of #417.
=> Nans deployment: fix tests

docs/api/covidcast-signals/ght.md, docs/api/covidcast-signals/hhs.md, docs/api/covidcast-signals/nchs-mortality.md, docs/api/covidcast_geography.md, docs/symptom-survey/contingency-tables.md
=> Fix a few more docs links

.github/workflows/create-delphi-epidata-release.yml
fix the branch name for creating the release PR
=> ci: fix branch for creating release

.bumpversion.cfg, src/client/delphi_epidata.R, src/client/delphi_epidata.d.ts, src/client/delphi_epidata.js, src/client/delphi_epidata.py, src/client/packaging/npm/package-lock.json, src/client/packaging/npm/package.json, src/client/packaging/pypi/setup.py
* add the `client_version` to all clients
* add the version function to the JS client using the new server version endpoint
* unify bumping all versions when triggering the GitHub Action
=> unify client versions and bump them at once

docs/symptom-survey/coding.md, docs/symptom-survey/problems.md
=> Describe French translation fix

src/server/_db.py, src/server/endpoints/covidcast.py
use SQLAlchemy to check whether the missing columns (`missing_value`, ...) exists in the covidcast table. If they to, query them, if they don't provide dummy values instead. 
This could be a workaround till we have the database updated
=> dynamically check if the missing_* columns exist

src/server/endpoints/covidcast.py
=> feat: add /covidcast/anomalies endpoint

src/server/endpoints/covidcast.py
small fixes for bugs I encounted
=> fix: trendseries serialization + require signal in coverage endpoint

integrations/acquisition/covidcast/test_covidcast_meta_caching.py, integrations/client/test_delphi_epidata.py, integrations/server/test_covidcast.py, integrations/server/test_covidcast_endpoints.py, integrations/server/test_covidcast_meta.py, integrations/server/test_fluview.py, integrations/server/test_fluview_meta.py, src/acquisition/covidcast/database.py
Finish the SQL query part and pass all the unit test and integrations test.
=> finish add SQL Query and pass the integrations tests

src/server/endpoints/covidcast.py
removes the workaround for the nan/missing columns
=> feat: remove missing workaround

docs/api/covidcast-signals/quidel.md
=> Update Quidel test_per_device description

docs/symptom-survey/server-access.md
Documents the solution to a common Cyberduck issue experienced by data users when trying to download large files.
=> Mention Cyberduck problem and solution

.github/workflows/update_gdocs_data.yml
closes 
Workflow failed due to filename misspell
=> Fix typo in meta sheet requirements file

docs/api/covidcast-signals/fb-survey.md
Added general overview of declining response rate/sample size in limitations section
=> Document declining survey response rate

src/server/utils/dates.py
I was to eager to click the merge button of #668
=> fix: fix tests for merging #668

docs/symptom-survey/problems.md
=> Document two sampling issues

src/server/endpoints/covidcast.py
add "basis_shift" param to /covidcast/trend and /covidcast/trendseries to specify in both variants easily how many days/weeks the basis for the trend should be before the current date
=> feat: add basis_shift param to /covidcast/trend

docs/symptom-survey/coding.md
Documents the deactivation of schooling items on Wave 11 for the summer.
=> Document schooling deactivation

docs/new_endpoint_tutorial.md
Remove remaining outdated materials
Less outdated than I thought (thanks sam) but still some minor things to fix
=> Update new endpoint tutorial

docs/symptom-survey/data-access.md, docs/symptom-survey/index.md, docs/symptom-survey/limitations.md, docs/symptom-survey/modules.md, docs/symptom-survey/problems.md, docs/symptom-survey/weights.md
* Add a page describing the limitations of the survey data and what it can best be used for
* Link to that page from other pages
* Add more detailed credits to the main page
* Fix an incorrect page title
* Add a link to the survey dashboard
Temporary preview link: http://rosmarus.refsmmat.com/delphi-epidata/symptom-survey/limitations.html
=> Document survey limitations, add credits, other survey doc fixes

docs/api/covidcast-signals/fb-survey.md, docs/symptom-survey/contingency-tables.md, docs/symptom-survey/survey-files.md
For API, microdata, and contingency tables, describe condition of dropping responses from Puerto Rico and other territories, linking to UMD's survey site.
Text adapted from limitations doc :smile:
=> [survey] Describe regional requirement for inclusion

docs/api/covidcast-signals/fb-survey.md, docs/symptom-survey/data-access.md
Switch to new FB data access links.
=> Update FB links in survey docs

src/server/_printer.py
closes #760
fixes non standard messages and also include the compatibility mode
=> fix: add compatibildity mode for non_standard_message

docs/api/covidcast-signals/nchs-mortality.md
[This paper](https://doi.org/10.1057/s41271-021-00309-7) provides some useful analyses of NCHS mortality backfill characteristics.
Add one link to NCHS docs.
=> Point to analysis of NCHS backfill in docs

docs/api/covidcast-signals/chng.md
We're working on reactivating the CHNG pipeline, although it looks like there are some data delivery problems with the SFTP site. Once those are resolved, we should update the reactivation dates in this PR and merge it.
=> Update chng pause status

docs/api/covidcast_licensing.md, docs/symptom-survey/index.md
Points to our brand-new PNAS papers in the documentation, so they can be cited by data users (and so people can read them to learn about the data!).
=> Point to our PNAS papers for citations

docs/symptom-survey/coding.md, docs/symptom-survey/contingency-tables.md, docs/symptom-survey/problems.md
Several updates to the survey documentation.
* Document the released version of Wave 12
* Document how race/ethnicity items are coded
* Mention temporary sampling outage
* Don't point to `OUTAGES.txt`, since we don't use it
=> Wave 12 updates, survey outages, etc.

docs/api/covidcast-signals/quidel.md
Fixes #810 
- Add newly added signals with age grouops
- Update the description of signals to indicate the age groups infomation
=> Add age-specific signals

docs/api/covidcast-signals/google-symptoms.md
closes 
updating google symptoms signal names
=> changing signal names

src/client/packaging/npm/package-lock.json
Cross-fetch was blocking a dependabot security update; this should fix it. Resulted from:
```
src/client/packaging/npm $ npm audit fix
```
=> Update cross-fetch; fixes dependabot vulnerability no. 4

docs/api/covidcast-signals/quidel.md
closes[ #838](https://github.com/cmu-delphi/delphi-epidata/issues/838)
- Add county, HHS, national level description
- Add more details to the smoothing process
=> Update Quidel doc

.github/workflows/ci.yaml
We need to build containers from this branch in preparation for v4 migration.
=> Update workflow to build container images from branch

docs/api/covidcast-signals/quidel.md
closes #875 
Add description to the limitation of availability for some age groups.
=> state the limitation of the availability

docs/symptom-survey/coding.md
We neglected to say this explicitly, so the only way to find out is to check the codebook spreadsheet. I often find survey items by searching the coding page, so it's useful to be explicit here.
=> Mention that V15a was renamed to V15c

tests/server/test_pandas.py
* test_pandas.py: this test is just supposed to verify that we're using the right row limits when running `as_pandas`, and doesn't really need a database connection. Mock out the sqlalchemy and pandas functions and just check that everything is hooked up properly.
=> Fix test_pandas for v4

integrations/acquisition/covidcast/test_csv_uploading.py
* check signal_* tables instead of covidcast
* remove direction checks
=> v4: Fix test_csv_uploading

docs/symptom-survey/end-of-survey.md, docs/symptom-survey/index.md
Describes the end date of CTIS and the reasoning for it. **Not ready to be merged**; needs updating with a link to wherever UMD's equivalent page will be, so we can point to their schedule and reasoning.
Provided UMD is able to post their site, we'd like to deploy this around 9am ET on Friday, April 8.
=> New page describing the planned end date of CTIS

docs/symptom-survey/weights.md
Meta has developed a new Weights User Guide to replace the old PDF guide, so point to that instead.
=> Point to new weights user guide

docs/api/covidcast-signals/jhu-csse.md
closes #679
Issue:
the available for line of JHU Cases and Deaths page need to update with 'hhs' and 'nation'
Fix:
1. update the line with elements 'hhs' and 'nation'
=> 1. updated the available for line

docs/api/covidcast-signals/fb-survey.md, docs/symptom-survey/coding.md, docs/symptom-survey/end-of-survey.md, docs/symptom-survey/index.md
Provide links to the CTIS Methodology Report in the documentation, and note on the API documentation that the survey has ended.
=> CTIS methodology report links

devops/Dockerfile, requirements.txt, src/server/_config.py, src/server/_query.py
Reverts cmu-delphi/delphi-epidata#973
merged too soon...  rolling back temporarily so as not to disrupt automation routines until the changes are scheduled to be deployed.
=> Revert "TEST - Build and image with new Flask and SQLAlchemy"

.github/workflows/ci.yaml
=> revert ci config change

package-lock.json, package.json
closes #980
Just a minor clean in the morning.
=> Fix repo pointers in package.json and package-lock.json

.github/workflows/ci.yaml
We need to build an image for testing. It can be reverted after success.
=> Build a container image from this branch

devops/gunicorn_conf.py
Reverts cmu-delphi/delphi-epidata#1013
=> Revert "Increase Gunicorn's idle timeout"

src/server/endpoints/ecdc_ili.py, src/server/endpoints/flusurv.py, src/server/endpoints/fluview_clinicial.py
Followup to https://github.com/cmu-delphi/delphi-epidata/pull/1062 adding several missing imports.
=> Fix missing imports in endpoints

docs/api/covidcast-signals/_source-template.md
So far, this is just an update to the source template to encourage new sources to document when they are missing and what kinds of missingness are possible.
Before merging, we should add documentation for each existing source when applicable.
=> Document missingness of each signal

docs/symptom-survey/end-of-survey.md, docs/symptom-survey/index.md, docs/symptom-survey/publications.md
See https://github.com/cmu-delphi/www-main/issues/730
Creates a new page under the CTIS section with a list of results, and updates the index page to make it easier to find survey results and publications.
=> Create a new page for publications using CTIS

docs/symptom-survey/publications.md
New publication, and update a couple past ones.
=> New CTIS publication + updates

docs/symptom-survey/publications.md
Adds three more CTIS publications, and updates one that got a final publication date/issue.
=> Add 3 more CTIS publications

.github/workflows/ci.yaml
=> Updated ci.yaml

.github/workflows/ci.yaml
=> Changed wrong redis host name

requirements.api.txt, requirements.dev.txt, src/server/_security.py, src/server/endpoints/covidcast_utils/dashboard_signals.py, src/server/endpoints/covidcast_utils/descriptions.raw.txt, src/server/endpoints/covidcast_utils/questions.raw.txt
to access the list of signals used by the frontend/dashboard
use like:
```
from delphi.epidata.server.endpoints.covidcast_utils.dashboard_signals import DashboardSignals
sigs = DashboardSignals().srcsig_list()
```
=> dashboard signals module

docs/api/api_keys.md
=> Fix link to privacy statement

docs/symptom-survey/publications.md
And fill out bibliographic details for a couple older ones.
=> New CTIS publication

src/acquisition/fluview/fluview_notify.py, src/acquisition/fluview/fluview_update.py, src/acquisition/fluview/impute_missing_values.py
Specified database host in database connection strings to avoid wrong database using.
=> Added host to database connection

src/acquisition/covidcast/test_utils.py
also removed some trailing whitespace
=> remove rate-limiting info from redis before each test

docs/symptom-survey/publications.md
=> Newer CTIS publication

docs/symptom-survey/publications.md
They're coming pretty fast in the last few weeks.
=> Newest CTIS publication

integrations/server/test_covidcast_endpoints.py
Added integration tests for covidcast `/` endpoint
=> Added integration tests for covidcast / endpoint

.github/workflows/ci.yaml, .github/workflows/create-release.yml, .github/workflows/missing_signals.yaml, .github/workflows/release-helper.yml, .github/workflows/update_gdocs_data.yml
temporarily reverting changes from #1273 and #1262, as theyre not fully ready yet
=> Temporarily revert CI update commits

docs/api/fluview.md
closes|addresses 
Fix broken links for HHS regions and census divisions
=> Fix broken links for HHS regions and census divisions

.github/workflows/performance-tests.yml
Adds an extra step to the performance test runner which cleans up files from previous (now self-hosted) runs.
=> Cleanup files from previous runs of performance test rig

src/server/endpoints/covidcast_utils/descriptions.raw.txt
Syncing covidcast_utils files to www-covidcast release v3.2.9.
=> Sync to www-covidcast release v3.2.9

docs/api/covidcast-signals/hospital-admissions.md
Added blog post link to hospital-admissions
=> Added blog post link to hospital-admissions

docs/api/covidcast-signals/chng.md
Added "Backfill" blog post link to covidcast chng signal.
=> Covidcast chng signal: added "backfill" blog post link

docs/symptom-survey/publications.md
=> Add the 49th and 50th CTIS publications

docs/api/covidcast-signals/jhu-csse.md
Added below, which were not listed in documentation: confirmed_7dav_cumulative_num
confirmed_7dav_cumulative_prop
deaths_7dav_cumulative_num
deaths_7dav_cumulative_prop
closes|addresses
=> Added four signals to jhu-csse documentation

docs/api/covidcast-signals/nchs-mortality.md
Updated broken link to CDC epiweek and checked changes on locally built site.
=> Updated broken link to CDC epiweek

docs/api/covidcast-signals/jhu-csse.md
Moving JHU to inactive section
[ ] Unless it is a documentation hotfix it should be merged against the `dev` branch
[x ] Branch is up-to-date with the branch to be merged with, i.e. `dev`
[ ] Build is successful
[ ] Code is cleaned up and formatted
=> Moving JHU to inactive

docs/symptom-survey/publications.md
=> Another CTIS publication

src/client/packaging/pypi/CHANGELOG.md
i plan/hope to do the release on monday the 20th
=> Update CHANGELOG.md w/ expected release date

src/client/packaging/pypi/CHANGELOG.md
=> fix boneheaded version typo in CHANGELOG

docs/api/covidcast-signals/quidel.md, docs/api/covidcast_licensing.md
Followup to https://github.com/cmu-delphi/delphi-epidata/pull/1476
=> Correct indicator combo and quidel links

docs/epidata_development.md
cleans up comments from #1466 
Add a helpful docker command.
=> docs: very minor dev doc update

docs/api/covidcast-signals/covid-act-now.md
Update Covid act now doc page with more context, plus some wording  cleanup.
=> Covid act now source links and context around deactivation

docs/api/README.md
Clarify which diseases are available where.
Closes https://github.com/cmu-delphi/delphi-epidata/issues/1398
=> other endpoints intro

docs/symptom-survey/publications.md
=> New CTIS publications

docs/api/covidcast-signals/google-symptoms.md
=> Add `google-symptoms` data dip message

docs/api/covidcast-signals/nssp.md
addresses issue(s) #2074
Add documentation for 2023RVR nssp signals.
=> Add documentation for 2023RVR nssp signals

src/server/endpoints/covidcast_utils/descriptions.raw.txt
Syncing covidcast_utils files to www-covidcast release v3.2.11.
=> Sync to www-covidcast release v3.2.11

docs/api/covidcast-signals/google-survey.md, docs/api/covidcast-signals/indicator-combination.md, docs/api/covidcast-signals/safegraph.md, docs/api/covidcast-signals/usa-facts.md
Makes updates to COVIDcast inactive signals: 	
google-survey.md
indicator-combination.md
safegraph.md
usa-facts.md
=> Updates to COVIDcast inactive signals.

docs/symptom-survey/publications.md
=> Add new publication and update older ones

.github/workflows/performance-tests-one-time.yml, .github/workflows/performance-tests.yml, docs/api/covidcast-signals/google-survey.md, docs/api/covidcast-signals/indicator-combination.md, docs/api/covidcast-signals/nhsn.md, docs/api/covidcast-signals/nssp.md, docs/api/covidcast-signals/safegraph.md, docs/api/covidcast-signals/usa-facts.md, docs/symptom-survey/publications.md, tests/server/test_pandas.py
=> Remove JHU signals from documentation

docs/api/covidcast-signals/google-symptoms.md
=> Clarify signals affected by `google-symptoms` dip
