src/acquisition/ght/ght_update.py
src/acquisition/ght/google_health_trends.py

Added optional two-letter country argument to ght_update, as required by the google health trends API.
Nothing should change for the US. Other countries are now saved in the server database with location "XX_" where XX denotes the ISO 1366 alpha-2 country code.

Enable ght parsing of countries other than US

---

src/acquisition/norostat/norostat_raw.py

CDC updated the format of
https://www.cdc.gov/norovirus/reporting/norostat/data-table.html changing
capitalization and wording in the table explanation, breaking the current
scraper. Update the scraper to handle the new format (as well as the old).
Changes to page causing breakage:
- "Suspected and Confirmed Norovirus Outbreaks Reported by State Health
Departments" -> all lower case; handle by being case insensitive for SCNORHD
- "to the" -> "through the"; handle by matching either of these

Update norostat xpath&regexes to handle new data-table.html format

---

deploy.json
src/acquisition/wiki/wiki_download.py

The error raised is `ImportError: No module named wiki_util`
I am always tortured by the python's path finding mechanism. So, here I use two methods to cope with this error.
1. copy the `wiki_util.py` file to the same directory with wiki_download.py
2. Use the same import format as shown in `wiki.py` (although this cannot run in my local environment)

Fix a bug in deploying

---

src/acquisition/afhsb/afhsb_sql.py

LOAD DATA LOCAL INFILE has security issues when used with untrusted servers and
is disabled by default in some versions of MariaDB.  Change back to using LOAD
DATA INFILE and ensure that afhsb_data directory is readable by the account
running the MariaDB server daemon.

Change back to LOAD DATA INFILE in afhsb_sql.py

---

src/acquisition/afhsb/afhsb_sql.py
src/acquisition/afhsb/afhsb_update.py

MariaDB appears to refuse to LOAD DATA INFILE except on files under
/var/lib/mysql (which seems dedicated to its own files) or /tmp; create a
temporary directory, make rwx for automation & rx for mysql user, copy in
args.datapath to the temporary directory, then run init_all_tables on this
temporary datapath.
Add afhsb_sql.dangerously_drop_all_afhsb_tables function to allow for more rapid
iteration on acquisition code, which stops when encountering a partially or
fully initialized set of AFHSB database tables.
Remove __main__ functionality from afhsb_sql.
Add argparse functionality to afhsb_update to allow for --datapath argument
to override default afhsb_data directory path.

Use tmp dir to work around LOAD INFILE restrictions; add helper funs

---

docs/README.md

turns out *github* renders link text that spans lines, no problem. but 
*github pages* chokes on link text that span lines, instead linking to 
the raw markdown rather than the rendered html as intended.
lesson learned the hard way: one line per link.

fix docs/readme

---

integrations/test_covidcast_meta.py
src/server/api.php

- this is consistent with the `data_source` parameter of the `covidcast` 
endpoint
- ✔ All 9 tests passed!

covidcast_meta alias source as data_source

---

docs/api/covidcast.md
docs/api/covidcast_meta.md
docs/api/wiki.md
integrations/test_delphi_epidata.py
src/client/delphi_epidata.R
src/client/delphi_epidata.coffee
src/client/delphi_epidata.js
src/client/delphi_epidata.py

add `covidcast` and `covidcast_meta` endpoints to clients, add integration tests for the python changes, and add documentation to the corresponding api docs. also some other minor fixes.
testing: the new integration tests pass.

Add covidcast and covidcast_meta endpoints to clients

---

docs/api/covidcast.md
docs/api/covidcast_meta.md
integrations/client/test_delphi_epidata.py

update examples in `covidcast` and `covidcast_meta` docs and integration tests to:
* switch '_' with '-' in data source names.
* add new fields in responses.
* use 'cli' signal instead of 'ili' since these sources are focused on covid.
testing:
* all unit tests pass
* all integration tests pass

update covidcast docs and tests to account for schema changes

---

src/acquisition/cdcp/cdc_upload.py
src/acquisition/flusurv/flusurv.py
src/acquisition/fluview/fluview.py
src/acquisition/norostat/norostat_raw.py
src/acquisition/wiki/master.php
src/acquisition/wiki/wiki_download.py

replace remaining instances of "delphi.midas[.cs].cmu.edu" with "delphi.cmu.edu". the ide also fixed some errant carriage returns in the `wiki/master.php` file.
testing: all unit and integration tests pass.

replace remaining delphi.midas.cs.cmu.edu with delphi.cmu.edu

---

integrations/test_deploy_syntax.py

- editing `deploy.json` is error-prone due to the strict parsing 
requirements of JSON
- many past prod deployments have failed due to simple mistakes, like 
missing or extra commas
- this test ensures that `deploy.json` is at least syntactically valid

`deploy.json` syntax test

---

integrations/acquisition/covidcast/test_covidcast_meta_caching.py
src/acquisition/covidcast/covidcast_meta_cache_updater.py
src/acquisition/covidcast/database.py
src/ddl/covidcast.sql
src/server/api.php

- use a short-lived cache to make `covidcast_meta` super fast
- integration tested
- all unit and integration tests pass
- i owe unit tests for this

covidcast_meta optional caching

---

tests/acquisition/covidcast/test_covidcast_meta_cache_updater.py

- missing `argparse`
- worked before because py3tester included it, but should have been 
explicitly included anyway

add missing import

---

docs/epidata_development.md
docs/new_endpoint_tutorial.md

- walks through the process of adding the new `fluview_meta` endpoint

add tutorial for adding a new endpoint

---

src/acquisition/covidcast/csv_importer.py
tests/acquisition/covidcast/test_csv_importer.py

- strings where numbers are expected shouldn't cause the importer to 
crash
- catch ValueError and report the field as invalid
- add unit tests which would have caught this failure mode
- unit and integration tests pass

protect against failed type casts

---

integrations/server/test_covidcast_meta.py
src/server/api.php

- in covidcast_meta, don't return signals named like "wip-*"
- this lets delphi iterate on modelling decisions before surfacing a 
signal for outside consumption
- added integration test for this case
- all unit and integration tests pass

suppress covidcast meta for WIP signals

---

integrations/acquisition/covidcast/test_covidcast_meta_caching.py
integrations/acquisition/covidcast/test_csv_uploading.py
integrations/server/test_covidcast_meta.py
src/server/api.php

* Dash fouls up the acquisition regexes, and it's not clear what other parts of the pipeline will balk at them
* Underscore is already successfully in use as part of signal names
* Change SQL exclusion clause for WIP signals
* Change integration test for WIP signals
* Add acquisition tests for WIP signals
All tests pass in docker.

Switch WIP signifier from dash to underscore

---

docs/api/covidcast.md
docs/api/covidcast_signals.md

Continuing from #105, which I accidentally merged too soon and reverted.
This adds
* megacounty documentation
* end of routine Google Survey operation
* suspension of Quidel operation
* new combination signal
See also #109, which should be merged at the same time.

v1.2 documentation update

---

docs/api/covidcast.md
docs/api/covidcast_signals.md

See commit messages -- just fixing headers and the links to the clients, plus other small link issues.

Fix some headers and links in the COVIDcast documentation

---

docs/api/covidcast_signals.md

Fixes the API docs for the updated combination signal, and fixes the table showing the signals included in the map.
Will merge only after the 1.2.1 site update goes live.

Update to 1.2.1 combination signal, and fix map table

---

docs/api/covidcast_changelog.md
docs/api/covidcast_signals.md

* Creates a new page to hold the changelog
* Prototypes a changelog format that balances completeness with concision
* Adds references to changelog in each source section of `_signals.md`
We may want to pick a different anchor date, particularly for Quidel and Google Surveys.

List data changes from cmu-delphi/covidcast-indicators#47 in a changelog

---

integrations/acquisition/covidcast/test_csv_uploading.py
src/acquisition/covidcast/csv_importer.py

Fixes #120 by just failing the files at acquisition time. I can then do a pass through the database and drop all the truncated signals.

Reject covidcast CSV files with signal names that are too long

---

integrations/acquisition/covidcast/test_covidcast_meta_caching.py
integrations/acquisition/covidcast/test_direction_updating.py
integrations/client/test_delphi_epidata.py
integrations/server/test_covidcast.py
integrations/server/test_covidcast_meta.py
src/acquisition/covidcast/csv_importer.py
src/acquisition/covidcast/csv_to_database.py
src/acquisition/covidcast/database.py
src/ddl/covidcast.sql

* Database schema change in ddl (Brian please double-check)
* Supporting infra in acquisition
* Extend all data insertion test cases to include toy issue and lag
* Test that we can insert a new issue for an extant (source,signal,date,geo)

Add columns to covidcast for issue and lag.

---

src/acquisition/covidcast/csv_importer.py

Indicators will do their own sample size validation from here on out.
This is necessary for the safegraph indicator, which uses a special definition of sample size (requested by forecasting) that is not based on individual users but on clusters.

Remove minimum sample size requirement.

---

docs/api/covidcast.md
docs/api/covidcast_signals.md

Clarify how geographies are identified; expand examples; and list the signal updates from v1.3.

Further expand/improve COVIDcast API docs

---

docs/epidata_development.md
tests/acquisition/covidcast/test_csv_importer.py

The deploy of #126 failed because of failing unit tests. Unit tests were not included in the developer guide, so I've added a section describing how to run them. The failing test has been fixed (we no longer want acquisition to fail on a sample size < 5), and all tests pass.

Remove minimum sample size test; include unit tests in dev guide

---

src/client/delphi_epidata.R
src/client/delphi_epidata.py
src/client/packaging/pypi/setup.py

The overhead for the non-cached endpoint is substantial.
(I'm going to check if David can push a new version of `delphi-epidata` to PyPI for us, so we can release a Python package that has fast access to the metadata without monkey-patching the current version.)

Make metadata requests use the cached endpoint automatically

---

src/acquisition/covidcast/direction_updater.py

Stopgap for the dreaded Direction crashes. This will skip direction on signals that don't have an entry in the output of `database.get_data_stdev_across_locations`  (which cuts off at 22 April 2020)

Skip computing direction on signals without enough history

---

docs/_config.yml
docs/_includes/head_custom.html
docs/api/covidcast-signals/_source-template.md
docs/api/covidcast-signals/doctor-visits.md
docs/api/covidcast-signals/fb-survey.md
docs/api/covidcast-signals/ght.md
docs/api/covidcast-signals/jhu-csse.md
docs/api/covidcast_signals.md

Based on covid-19's signal_descriptions.tex file, ported to Markdown and with some copyedits.
Remaining:
[Preview of this branch's documentation](http://rosmarus.refsmmat.com/delphi-epidata/api/covidcast_signals.html).

WIP Add technical descriptions to API documentation

---

src/client/delphi_epidata.py

This will help us track what proportion of API users are from each client.
I don't think we need to cut a new delphi-epidata release on PyPI yet; this will just be good to have when we do.

Provide a User-Agent string in delphi_epidata.py

---

docs/api/covidcast-signals/ght.md

Currently anosmia. Not pushing yet, because this is subject to
correction once we investigate. See
https://github.com/cmu-delphi/covidcast-indicators/issues/138

Document the terms used in GHT

---

docs/api/covidcast.md
docs/api/covidcast_meta.md

This
* documents the new columns in the metadata (although I'm not sure I interpreted min_lag and max_lag correctly?)
* slightly expands the text about as_of/issues/lag.
The client API docs will have extended examples on fetching issue dates, which is what I expect the users to most rely upon.

Issue lag docs

---

src/client/packaging/pypi/delphi_epidata/__init__.py
src/client/packaging/pypi/setup.py

So the updated covidcast client can depend on 0.0.7 and ensure it has as-of and issue support.

Bump delphi-epidata version number

---

docs/api/covidcast.md

Based on the styling Sphinx uses in the Python docs. Unfortunately
Markdown is not parsed inside block HTML elements like divs, so the
whole block must be raw HTML, but it works.
Demo: http://rosmarus.refsmmat.com/delphi-epidata/api/covidcast.html

More aggressively advertise the API mailing list

---

src/server/api.php

Resubmitting PR #104 to main branch.  This should fix the "norostat" endpoint.
Can test in R client with
```
Epidata$norostat(auth="(auth token)","Minnesota, Ohio, Oregon, Tennessee, and Wisconsin",epiweeks=Epidata$range(100052,300052))
```
Broken behavior: no results (-2).
Fixed behavior: epidata and success code.

Remove garbage characters in get_norostat query

---

integrations/acquisition/covidcast/test_csv_uploading.py
src/acquisition/covidcast/csv_importer.py
src/ddl/covidcast.sql

* Database schema
* Signal name length guard in CSV uploader
* Integration test verifies signal length 32<x<64 succeeds, x>64 fails
Unit tests and integration tests pass.
To apply this to the live DB, use the following:
```
ALTER TABLE `covidcast`
MODIFY `signal` varchar(64) NOT NULL;
```

Increase maximum signal length for COVIDcast to 64 characters

---

docs/index.md

Now that it will be linked in the nav bar, make it easier to find what
you want.
@zackchase This will replace the page here: https://cmu-delphi.github.io/delphi-epidata/
Since it'll be in the nav bar, best to polish it and make it inviting so they quickly see how to find the data they want. Feel free to edit/polish.

Make the API doc home page more welcoming

---

src/server/.htaccess

See #160 -- this will only help if deployed to the AWS API endpoints at api.covidcast.cmu.edu, since those run Apache and the others run nginx.
This assumes we have mod_deflate and mod_brotli available on those servers.

Enable gzip/brotli compression and caching of API responses

---

src/server/.htaccess

I think enabling expires will require `AllowOverride Index`, or something like it, in the main Apache conf. So let's settle for enabling compression alone.
It's a hack to only have the Expires directives commented-out, but hopefully we can soon figure out how to set the Apache config appropriately.
I've tested on staging and the compression seems to work.

Enable compression but not caching

---

docs/symptom-survey/index.md

The link changed as people were tweaking the nav.
Merge once the new site is pushed live.

Fix link to surveys page

---

integrations/acquisition/covidcast/test_covidcast_meta_caching.py
integrations/acquisition/covidcast/test_csv_uploading.py
integrations/acquisition/covidcast/test_direction_updating.py
integrations/client/test_delphi_epidata.py
integrations/server/test_covidcast.py
src/acquisition/covidcast/csv_to_database.py
src/acquisition/covidcast/database.py
src/client/delphi_epidata.R
src/client/delphi_epidata.coffee
src/client/delphi_epidata.js
src/client/delphi_epidata.py
src/server/api.php
src/server/api_helpers.php

Fixes cmu-delphi/covidcast-indicators#116
* backwards-compatible signal/signals parameter
* optional 'format' parameter for retrieving results as a tree (preferred by Viz) or as a flat list (backwards-compatible); defaults to flat list
* client support: coffee, js, R, py
* integration tests to check multi-signal queries and queries for tree format

Add support for querying multiple signals

---

integrations/server/test_covidcast.py
src/server/api.php
src/server/api_helpers.php

add support for `format=csv` and `format=json`. The former creates a CSV file the later a raw JSON array.
To support the different messages, http status codes (500, 401, 400) are used which will in an error case also send the json object back

csv and raw json

---

src/client/delphi_epidata.R

#210 accidentally clobbered the default `format` parameter I was using in the R client, because R doesn't have as nice default-specification capabilities as coffee and python.
This only affects people still using the raw Epidata clients for COVIDcast, which notably includes the combination indicator.

Fix bad default 'flat' value for format parameter in raw R client

---

docs/api/covidcast-signals/hospital-admissions.md

Include claims averaging in documentation. Not sure the last equation is necessary, I just wanted to be clear about the averaging (we are using a weighted average of the two streams, where the weight is given by the denominators/total admissions). If you think it's confusing, please feel free to remove.

Update hospital-admissions.md for claims averaging

---

docs/api/covidcast-signals/doctor-visits.md
docs/api/covidcast-signals/hospital-admissions.md

Clarify that this backwards padding is not specifically for adjusting reporting delay (backfill), but rather to deal with data sparsity issues (which occur regardless of backfill).

Backfill->Backwards padding

---

docs/api/covidcast.md
docs/api/covidcast_signals.md

And other miscellaneous improvements.

Link docs to public repos

---

integrations/server/test_covidcast.py
src/server/api.php

closes #221 (single geo type only for now)
add support for `geo_values`.
valid variants:
* `geo_value=*`
* `geo_value=CA`
* `geo_values=CA,NY`

feat: support geo_values (single geo_type)

---

src/acquisition/covidcast/database.py
tests/acquisition/covidcast/test_database.py

Currently the return statement is inside of the `finally` block, this means that if an exception is caught and re-raised by the `except` block, it will be cached but then immediately discarded -- i.e., the function will never re-raise the exception. This will cause inserts that result in an exception to appear successful (though I believe with 0 lines inserted).
See https://stackoverflow.com/questions/43830803/re-raising-the-exception-doesnt-work-with-finally-clause for more context on the try/except/finally behavior.
This is an additional fix for #203.

Make sure that exceptions are reraised if the SQL insert fails.

---

src/server/api.php

closes #223 
in case no special flag is set (issues, as_of, lag) it will simplify the query to `is_latest_issue is TRUE` instead of a complex sub query
I would be curious how much faster this query is compared to the previous one. However, I cannot test it since my local database doesn't have enough data to be able to observe an effect

feat: use is_latest_issue in PHP

---

integrations/acquisition/covidcast/test_fill_is_latest_issue.py
src/acquisition/covidcast/fill_is_latest_issue.py

this should do the trick, but updating by id instead of the join coming shortly

updates to address JHU is_latest (issue #329)

---

src/acquisition/covidcast/database.py

in practice, we will probably not see issues with this unless we get some insanely large file to process, but with recent issues, i think this prudent.  there may be some performance drawbacks to this, but seeing as how the failure mode is silent, i think this is worth it.

TEMPORARY TABLE is evil

---

docs/api/covidcast-signals/usa-facts.md
docs/api/covidcast_changelog.md

Log usafacts geo refactor in changelog.
Fixes cmu-delphi/covidcast-indicators#415

Docs usafacts geo changelog

---

docs/api/covidcast-signals/fb-survey.md

Raw signals are not listed for the other indicators, so we only need this comment for the CLI/ILI signals.
cc @dshemetov, who couldn't find the information he needed because of this issue.

Mention smoothed fb-survey signals closer to raw signal discussion

---

docs/api/covidcast-signals/changehc.md

Apparently on browsers, math display requires $$, not $. RStudio uses a single $.

Replace $ to $$

---

docs/api/covidcast-signals/chng.md

It used to link directly to CC, and worse, the 2.0 version of the license. Now it links to the covidcast licensing page, which is correct.

Fix CHNG license link

---

src/server/.htaccess

#210 added format=csv, but these responses are not currently compressed like JSON responses are.
I'd like to switch to CSV format in the R client, so compression is important to add here.

Compress CSV responses from the API

---

src/client/packaging/pypi/delphi_epidata/__init__.py
src/client/packaging/pypi/setup.py

([this has already been deployed](https://pypi.org/project/delphi-epidata/0.0.8/); just logging here as a PR for posterity)

delphi_epidata PyPI version bump: 0.0.8

---

docs/api/covidcast-signals/google-symptoms.md
docs/api/covidcast-signals/safegraph.md

We missed some header misspellings, so this PR will make the new signals actually visible...

1.11 docs: Fix markdown headers

---

docs/api/covidcast-signals/chng.md

part of https://github.com/cmu-delphi/covidcast-indicators/issues/591. Wait to merge until CHNG CLI is running in production.

Change CLI docs

---

docs/api/covidcast-signals/nchs-mortality.md

Adds nchs-mortality.md.
This is the same as the text from [this mysteriously closed PR](https://github.com/cmu-delphi/delphi-epidata/pull/264) (past-krivard, what were you doing?), plus first issue and data licensing information.

Release NCHS Mortality

---

src/acquisition/covid_hosp/state_timeseries/test_utils.py

- don't look for specific repo name, but look for the testdata directory 
directly
- should fix the deploy of delpi-epidata, which currently fails due to 
unit tests failing due to being unable to find test data

fix search for testdata

---

docs/api/covidcast-signals/_source-template.md
docs/api/covidcast-signals/chng.md
docs/api/covidcast-signals/doctor-visits.md
docs/api/covidcast-signals/fb-survey.md
docs/api/covidcast-signals/ght.md
docs/api/covidcast-signals/google-survey.md
docs/api/covidcast-signals/google-symptoms.md
docs/api/covidcast-signals/hospital-admissions.md
docs/api/covidcast-signals/indicator-combination.md
docs/api/covidcast-signals/jhu-csse.md
docs/api/covidcast-signals/nchs-mortality.md
docs/api/covidcast-signals/quidel.md
docs/api/covidcast-signals/safegraph.md
docs/api/covidcast-signals/usa-facts.md
docs/api/covidcast.md
docs/api/covidcast_inactive_signals.md
docs/api/covidcast_meta.md
docs/api/covidcast_times.md

List the formats and how to interpret them. List available time types for every signal so users know what to request (since they *must* specify a time type to fetch a signal).

Document available time types and their formats more explicitly

---

integrations/acquisition/covid_hosp/facility/test_scenarios.py
src/client/delphi_epidata.R
src/client/delphi_epidata.coffee
src/client/delphi_epidata.js
src/client/delphi_epidata.py
src/server/api.php

- api udpated
- all clients updated
- added integration test which exercises the new endpoint in server and 
python client
next pr will add another endpoint for hospital discovery. (e.g. answer "what hospitals are in PA?". then use that info to query `covid_hosp_facility` with a specific `hospital_pk` of interest.)
all unit and integrations pass

add endpoint `covid_hosp_facility`

---

integrations/acquisition/covid_hosp/facility/test_scenarios.py
src/acquisition/covid_hosp/common/utils.py
src/acquisition/covid_hosp/facility/database.py
src/client/delphi_epidata.R
src/client/delphi_epidata.coffee
src/client/delphi_epidata.js
src/client/delphi_epidata.py
src/ddl/covid_hosp.sql
src/server/api.php
tests/acquisition/covid_hosp/common/test_utils.py

- `bool('false')` is `True`
- add a helper function to parse bool from str, allowing missing and 
empty values
note that prod database needs to be backfilled since previous 
acquisitions incorrectly casted 'false' and 'true' both to `True`
---
- the hhs covid hosp dataset is keyed by `hospital_pk`, which is a 
unique identifier for healthcare facilities.
- the key is not generally well-known, but querying the 
`covid_hosp_facility` dataset requires key(s)
- the new endpoint returns facility information (including key) for 
given regions (e.g. city, state, zip, ccn, fips)
- users would be expected to lookup hospitals of interest e.g. by state 
or city. then query `covid_hosp_facility` with the key for those 
hospitals.
- server and clients updated
- all unit and integrations pass
note that …

facility fix and new endpoint

---

docs/symptom-survey/index.md

Our site didn't clearly explain who runs the survey and Delphi's role, and it did not tell data users how to cite the survey in publications.

Describe survey credits and citation requirements more clearly

---

docs/api/covidcast-signals/fb-survey.md

Currently preparing this signal for public release, so I'd like the docs to be ready when that happens (perhaps Wed Jan 6).

Document upcoming COVID vaccine acceptance signal

---

integrations/server/test_covidcast_nowcast.py

This got missed when we removed the backwards-compatible `signal` parameter that had been copy-pasted from covidcast

Correct nowcast parameter spelling in requests

---

src/acquisition/covidcast/csv_to_database.py
src/ddl/covid_hosp.sql
tests/acquisition/covidcast/test_csv_to_database.py

**WARNING** this PR includes a commit reducing the size of the covid_hosp_meta.revision_timestamp column from 1024 to 512. Nothing depends on that change except compliance with MariaDB maximum key length, but once this is merged we should make that change in prod. No value in that column is presently more than 23 characters, so shouldn't be an issue.
**Actual purpose:** Covidcast Acquisition currently counts the number of rows in the `covidcast` table regardless of whether the `receiving` directory is empty. This operation now takes upwards of 40 minutes, which is silly.
This PR rearranges the upload script somewhat so that it first checks `receiving`, then exits as a no-op if it finds no files.
In the process, I merged the default and with-specific-issue routines.
Unit tests updated and …

Covidcast upload early exit

---

src/acquisition/covidcast/database.py

Fixes #361.
All unit and integration tests pass.

COVIDcast meta: use is_latest_issue instead of joining to a subquery

---

docs/api/covidcast-signals/fb-survey.md
docs/api/covidcast_geography.md

This signal is already in the API, so this can be merged as soon as it's ready.
Note I've tried to explain that this signal differs from the CDC reporting -- currently it reports vaccination rates nearly twice as high as the CDC does. It's unclear why this disparity exists; the CDC data clearly lags behind actual vaccinations, but I don't know how much, and meanwhile the survey probably has biases and I don't know how big they are. Hopefully the note makes that clear.
Also I fixed a minor formatting problem in the geography docs.

Add vaccination uptake signal

---

src/acquisition/covid_hosp/state_daily/network.py

For some reason it's changed. I'm using the [metadata json](https://healthdata.gov/api/3/action/package_show?id=7823dd0e-c8c4-4206-953e-c6d2f451d6ed&page=0) from [this page](https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state)
EDIT: apparently I'm really bad at copy pasting

Update state daily dataset ID

---

docs/api/covid_hosp.md

On January 22 we made repairs to two issues of covid_hosp_state_timeseries data to unscramble their columns. It's good to write these kinds of things down.

Added repairs section to covid_hosp docs

---

integrations/acquisition/covidcast_nowcast/test_csv_uploading.py
src/acquisition/covidcast_nowcast/load_sensors.py
tests/acquisition/covidcast_nowcast/test_load_sensors.py

Since nowcasting uses sensor values computed as_of certain dates, the issue dates need to be the as_of dates and not datetime.today() like other acquisitions. These as_of dates are specified during sensorization (it calls the covidcast as_of indicator data to generate the sensors) and added to the files to be ingested as a new column.
cc @mariajahja

Have nowcasting acquisition use issue date from file

---

integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py
src/client/packaging/pypi/setup.py

To be used by covidcast client (to speed up indicator combo) and also in nowcasting. 
One thing to note is that running this on some machines and/or in jupyter can lead to this an issue that [requires you run these two lines to solve](https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python/56434301#56434301). For that reason I'm not sure we'll want to make this the default method in covidcast, since we don't have much control over people's environments. Adding those lines at the top of the client file seems to resolves it for me, but not sure if that'll hold universally. If it does, then we might be fine. If not, we could set a protected flag in covidcast for async that only our internal users/superusers will change. 
Summary of changes:
- …

Add async method to epidata

---

src/acquisition/covidcast_nowcast/load_sensors.py

Turns out  the previous context manager using `.begin()` handled the transaction, but not the connection :(. Updated to manage the connection so it doesnt one for each loop.

Update nowcast db connection

---

integrations/acquisition/covid_hosp/state_daily/test_scenarios.py
src/acquisition/covid_hosp/common/test_utils.py
src/acquisition/covid_hosp/state_daily/database.py
src/acquisition/covid_hosp/state_daily/network.py
src/acquisition/covid_hosp/state_daily/update.py
testdata/acquisition/covid_hosp/state_daily/revision_0127.html
testdata/acquisition/covid_hosp/state_daily/revision_0128.html
testdata/acquisition/covid_hosp/state_daily/revision_0129.html
testdata/acquisition/covid_hosp/state_daily/revision_0130.html
testdata/acquisition/covid_hosp/state_daily/revisions.html
tests/acquisition/covid_hosp/state_daily/test_database.py
tests/acquisition/covid_hosp/state_daily/test_network.py
tests/acquisition/covid_hosp/state_daily/test_update.py

Context: Daily update files are posted in batches of several days at a
time. Only the most recent file is surfaced through metadata, but all updates
are posted on the revisions page.
This PR adapts the state_daily pipeline to:
1. Fetch all files in the batch
2. Merge them (I checked with the Reich folks that this is the desired behavior)
3. Upload as a single issue based on the upload date (=date recorded in metadata)
This requires some substantial changes to Update and tests to account for and
mock out the pipeline differences to common, and minor changes to Network and
Database.
BeautifulSoup (`bs4`) was already listed in `operations.requirements.txt`, so it shouldn't need to be added to prod before merging.
Fixes #402

covid_hosp: fetch all files from daily batches

---

src/acquisition/covidcast/covidcast_meta_cache_updater.py
src/acquisition/covidcast/logger.py
tests/acquisition/covidcast/test_covidcast_meta_cache_updater.py

- Add a structured logger to the epidata repo
- Add logging for time taken to generate and update metadata
Progress on #403
Note that this needs structlog installed before running since this adds a new dependency.
The logger is a fork of the logger in delphi_utils. We can unify these if we extract delphi utils into a standalone package.

Add structured logger to epidata, and log metadata generation

---

src/acquisition/covidcast/covidcast_meta_cache_updater.py

Explcitly check for None args when extracting log file location (since main is called directly with None args for integration tests)

Explcitly check for None args

---

integrations/acquisition/covid_hosp/state_daily/test_scenarios.py

Some of the state_daily update PRs were opened before #371  and merged after, so this pytest-required import got missed

Fix import for state daily integration test

---

src/acquisition/covidcast/database.py
tests/acquisition/covidcast/test_database.py

Removing an old function. See [this slack thread](https://delphi-org.slack.com/archives/C013AH5N01E/p1613671692177000).

Remove unsed stdev function

---

docs/symptom-survey/coding.md
docs/symptom-survey/contingency-tables.md
docs/symptom-survey/data-access.md
docs/symptom-survey/index.md
docs/symptom-survey/server-access.md
docs/symptom-survey/survey-files.md
docs/symptom-survey/weights.md

Adds documentation for contingency tables. This is largely taken from the existing README, plus some formatting and intro. This page is nested under `COVID Symptom Survey`, between `Response Files` and 'Survey Weights`.
Adds information about this data source and aggregates in the API to the `data-access` page.

Add page to symptom surveys block to document contingency tables

---

docs/symptom-survey/contingency-tables.md

Jekyll still sucks at links that span linebreaks.

Fix broken link

---

src/acquisition/covidcast/csv_to_database.py
tests/acquisition/covidcast/test_csv_to_database.py

Verified that the new method can replace the old. This should reduce database operations on upload.
Fixes #424

Remove seperate row count from csv upload

---

integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py

- Added raise_for_status so 4xx and 5xx codes will raise properly
- Properly implemented simultaneous connection limit (interestingly, the default is 100)
- Lowered the limit to 50

Have async raise 4xx/5xx status codes and add connection limit

---

src/client/packaging/pypi/delphi_epidata/__init__.py
src/client/packaging/pypi/setup.py

This will let us release correct handling for 5XX and 4XX response codes and more polite batching.

bump delphi-epidata version to 0.0.12

---

docs/api/covidcast-signals/ght.md

Requests to the GHT API now generate the following error:
```
googleapiclient.errors.UnknownApiNameOrVersion: name: trends  version: v1beta
```
which means it's time to deactivate the `ght` COVIDcast source.

Move GHT docs to Inactive Signals

---

docs/api/covidcast-signals/fb-survey.md

Switches all signal names in tables and text to use weighted format. Add paragraph offering unweighted signals as low-latency alternative.
Closes #447.

Display weighted survey signals by default

---

docs/api/covidcast-signals/fb-survey.md

1. Break up the behavior section into subsections so the table isn't so
intimidatingly large.
2. Place current signals above discontinued counterparts when possible.

Reorganize fb-survey signals slightly

---

src/acquisition/covidcast/signal_dash_data_generator.py
src/ddl/signal_dashboard.sql
src/server/api.php
tests/acquisition/covidcast/test_signal_dash_data_generator.py

- Save last update time when writing updates (if greater than what is currently stored)
- Adjust API SQL to remove the now unnecessary nested query to find max time.
- Update SQL table defs to add the new last update fields
- Update tests
Improves #438

Persist last update time for signal dashboard

---

src/acquisition/covid_hosp/facility/network.py
src/acquisition/covid_hosp/state_daily/network.py
src/acquisition/covid_hosp/state_timeseries/network.py
tests/acquisition/covid_hosp/facility/test_network.py
tests/acquisition/covid_hosp/state_daily/test_network.py
tests/acquisition/covid_hosp/state_timeseries/test_network.py

The new healthdata.gov API has different dataset IDs for the metadata and the raw data, so adding that as an attribute.
e.g.
data: https://healthdata.gov/dataset/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/6xf2-c3ie
metadata: https://healthdata.gov/dataset/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/4cnb-m4rz

Add metadata IDs to hhs datasets

---

src/acquisition/covidcast/signal_dash_data_generator.py
src/ddl/signal_dashboard.sql
src/server/api.php
tests/acquisition/covidcast/test_signal_dash_data_generator.py

Changes:
- Add covidcast_signal to the dashboard signal defs
- Embed the coverage time-series in the status response
- Add missing ID condition to status
- Update tests
Improves #438

Include coverage time series in signal dash status

---

docs/api/covidcast-signals/safegraph.md

This shouldn't be a subsection of Weekly Patterns (it applies to both), and we should mention research on its biases.

Extend SafeGraph limitations section

---

docs/symptom-survey/contingency-tables.md

Nation and state tables, including old aggs and FB expansion aggs, are up on the Delphi AWPS site.

[fb-survey] Update contingency table links

---

pyproject.toml
src/server/_params.py
src/server/_query.py
src/server/endpoints/covidcast.py
tests/server/endpoints/test_covidcast.py
tests/server/test_params.py
tests/server/test_query.py

closes #389
in a backward compatibility way
supports alternative way to specify the three dimensions, see google doc
e.g., `/covidcast/?signal=src1:sig1&time=day:20201202&geo=state:*`

[flask]: add new parameter version: signal,time,geo

---

src/server/_params.py
src/server/_validate.py
src/server/endpoints/covidcast.py
src/server/endpoints/covidcast_utils/__init__.py
src/server/endpoints/covidcast_utils/dates.py
src/server/endpoints/covidcast_utils/trend.py
tests/server/endpoints/covidcast_utils/test_dates.py
tests/server/endpoints/covidcast_utils/test_trend.py

based on #481 
adds a new custom endpoint `/covidcast/trend` which computes the trend for a given date and window.
e.g.
http://localhost:5000/covidcast/trend?signal=fb-survey:smoothed_cli&geo=state:ny&date=20210401&window=20200101-20210402
will result in: 
note: I just have limited local test data, so results may vary in your system

[flask]: /covidcast/trend endpoint

---

docs/api/covidcast-signals/fb-survey.md

We issued schooling aggs data back to November -- reflect that in the earliest availability date in the docs. Standardize placement of paragraph describing naming of weighted vs unweighted indicators to before list of indicators. Appears once per indicator section.

[survey] Schooling + format updates

---

devops/Dockerfile
devops/start_wrapper.sh
requirements.txt

This PR does the following:
- Installs the New Relic Python agent.
- Adds a simple wrapper to help determine if we should start via `start.sh` or
with `new-relic run-program start.sh`.
- The wrapper makes a decision based on the existence of the `NEW_RELIC_LICENSE_KEY`
environment variable. This is configued in `delphi-ansible-web`. Additional
New Relic-specific configuration can be supplied in that repository as well.
- When enabled and started with the NR commands the container will log useful
APM data to Delphi's New Relic account.
See [https://docs.newrelic.com/docs/agents/python-agent/installation/install-python-agent-docker/]

Enable New Relic APM (application performance monitoring) reporting for the flask container

---

docs/api/covidcast-signals/fb-survey.md

Since this confused at least one user into thinking there were raw versions for all survey signals.

Only mention raw signals where they exist

---

integrations/server/test_covidcast_endpoints.py
src/server/_params.py
src/server/_query.py
src/server/endpoints/covidcast.py
src/server/endpoints/covidcast_utils/__init__.py
src/server/endpoints/covidcast_utils/trend.py

based on #484 
adds a new `/covidcast/backfill` endpoint that can be used to query all issues for a given signal/geo combo over a given period of time:
Based on this data, one can create a backfill profile and visualization

[flask]: add /covidcast/backfill endpoint

---

docs/api/covidcast_changelog.md

Both of these are inactive and have no changes. 
Fixes #501

Remove google survey and ght from changelog

---

docs/api/covid_hosp.md
docs/api/covid_hosp_facility.md
docs/api/covid_hosp_facility_lookup.md

Forgot to change these links after #445. Fixes #505. Also adds info about how the state data is a combination of the state timeseries and state daily datasets. Wasn't sure how much info we wanted to put on that, so currently just left it as close to the original text as possible.

Fix links in HHS API docs and add state_daily info

---

deploy.json

see https://github.com/cmu-delphi/github-deploy-repo/blob/main/src/actions/copymove.py#L138

build: match is required for globbing

---

src/server/endpoints/covidcast.py

see #520 comment that the orders were different

fix: same order as csv server

---

src/server/endpoints/covidcast.py

to only return a subset of the fields if needed

feat: support filtering fields in correlation, trend, and backfill

---

src/server/endpoints/covidcast_utils/meta.py

improves the heuristic used for the new covidcast/meta endpoint such that it better reflects certain corner cases

feat: tune heuristic for signal good/bad/neutral

---

docs/api/covidcast-signals/ght.md
docs/api/covidcast-signals/hhs.md
docs/api/covidcast-signals/nchs-mortality.md
docs/api/covidcast_geography.md
docs/api/missing_codes.md
docs/symptom-survey/contingency-tables.md

We changed PRIVACY -> CENSORED and UNKOWN -> OTHER, so updating the corresponding documentation. #417

Docs: update nans codenames

---

src/server/endpoints/covidcast.py
src/server/endpoints/covidcast_utils/__init__.py
src/server/endpoints/covidcast_utils/meta.py

e.g.:
adds more information about the signals
* is_cumulative
* is_smoothed
* is_weighted
* format = per100k | raw | raw_count | percentage | fraction
* related_signals ... list of signals in the same data source that are related (different set of flags)

add related signals to /covidcast/meta

---

.bumpversion.cfg
.github/workflows/create-delphi-epidata-release.yml
requirements.dev.txt
src/server/_config.py
src/server/main.py

closes #529 
add a simple version endpoint `/version` which returns the current epidata version. Moreover, start with Github Release Action workflow similar to www-main or www-covidcast. For now, it is just about bumping the version and merging dev to main

add version endpoint

---

integrations/client/test_delphi_epidata.py
requirements.dev.txt
requirements.txt
src/client/delphi_epidata.py
src/client/packaging/pypi/setup.py

Add a single retry if an exception is encountered when making a request to the Epidata endpoint. If the retry fails, the exception encountered is reraised.
Also learned about reset_mock() so slipped that into an old test.
Requires https://github.com/cmu-delphi/operations/pull/66 otherwise the CI will fail on the import

Add retry to Epidata request

---

.gitignore
docs/api/client_libraries.md
docs/api/flusurv.md
docs/api/fluview.md
docs/api/fluview_clinical.md
docs/api/gft.md
docs/api/nidss_dengue.md
docs/api/nidss_flu.md
docs/api/nowcast.md
docs/api/sensors.md
docs/api/wiki.md
src/client/delphi_epidata.d.ts
src/client/delphi_epidata.js
src/server/endpoints/wiki.py

except the signal_dashboard ... ones since they are more internal
added new endpoints
* twitter
* wiki
* kcdc_ili
reordered the client to match the alphabetical order of the endpoints
plus: make the wiki language parameter optional similar to the R client

add all endpoints to JS client

---

docs/api/covidcast-signals/indicator-combination.md

In theory a newline inside link text shouldn't cause a problem, but for some reason Jekyll isn't rewriting the URL on this one so maybe it's using a more conservative filter?
Fixes #531

Remove newline from link

---

integrations/server/test_covidcast_endpoints.py
src/server/endpoints/covidcast.py

e.g. `/covidcast/coverage?signal=fb-survey:smoothed_cli&geo_type=state&days=20` would return the state count between today and the last 20 days.
params
* `days=<int>` optional number of days back, default = 30
* `latest=YYYYMMDD` optional latest day, default = today
* `geo_type=only-county` special county geo_type which filters out mega counties
* `window=YYYYMMDD-YYYYMMDD` specify the time window to return the coverage for

add a simple coverage endpoint

---

src/client/delphi_epidata.R

Make `Epidata$covidcast` work using the default `format` argument, and make it reject unrecognized `format` arguments.
Note that this approach will require keeping the format default arg up to date with all valid options; if an additional format possibility is added but the default arg is not updated, then users attempting to use this formatting option will encounter an error message.
---
Before: default format arg produces error
```
> Epidata$covidcast("jhu-csse","confirmed_incidence_num","day","state","20210101","az")
Error in vapply(elements, encode, character(1)) :
values must be length 1,
but FUN(X[[7]]) result is length 2
```
Before: bogus format arg produces output
```
> Epidata$covidcast("jhu-csse","confirmed_incidence_num","day","state","20210101","az",format="bogus")
[Produces …
```

Use `match.arg` on covidcast endpoint `format` argument in R client

---

integrations/acquisition/covidcast/test_covidcast_meta_caching.py
integrations/acquisition/covidcast/test_fill_is_latest_issue.py
integrations/client/test_delphi_epidata.py
integrations/server/test_covidcast.py
integrations/server/test_covidcast_endpoints.py
integrations/server/test_covidcast_meta.py
integrations/server/test_fluview.py
integrations/server/test_fluview_meta.py
src/acquisition/covidcast/database.py

Reverts cmu-delphi/delphi-epidata#574, which included some untested changes. Normally we'd fix those in a new PR, but we need to do a release this morning, so i'm taking the quick-but-rude option, sorry about that

Revert "add minimum issue date to the metadata with some tests(merge to dev)"

---

deploy.json

Server is now containerized, so we don't need to do minification or any of the root_web stuff from github-deploy-repo anymore

Hotfix: Drop outdated tasks from deploy.json

---

.github/workflows/create-delphi-epidata-release.yml

`dev` didn't seem to be unique which is weird since it is working in other repos

ci: enforce origin/dev branch in creating release

---

docs/api/covid_hosp.md

see https://delphi-org.slack.com/archives/C013AH5N01E/p1623776262114400
fixes a small typo in the docs regarding the old name of an endpoint

docs: fix wrong endpoint url in covid_hosp

---

integrations/acquisition/covid_hosp/state_daily/test_scenarios.py
src/acquisition/covid_hosp/common/utils.py

Add support to the `update_dataset` function so that it can take in date ranges to pass to `issues_to_fetch`. It's not as precise as specifying individual URLs to acquire, but is simple because it uses existing functionality.
To use it to hopefully patch our missing issues, something like the following would get run on the prod server.
```
from delphi.epidata.acquisition.covid_hosp.state_daily.database import Database
from delphi.epidata.acquisition.covid_hosp.state_daily.network import Network
from delphi.epidata.acquisition.covid_hosp.common.utils import Utils
Utils.update_dataset(Database, Network, date(2021, 6, 10), date(2021, 6, 13))
```
from the prod server. We should test on staging first.
Also fixed a random old docstring to be a bit more clear.

Add issue range arguments to update dataset function

---

src/client/packaging/pypi/delphi_epidata/__init__.py

We missed a spot when setting the client versions to 0.1.0 uniformly

Set self-reported python client version to 0.1.0

---

src/ddl/covidcast.sql

I believe this is correct but @korlaxxalrok can correct me
Fixes #593

COVIDcast: update database definition to match BIGINT fix

---

integrations/server/test_covid_hosp.py
src/server/endpoints/covid_hosp_state_timeseries.py

closes 
Bug fix: Previously as_of was returning all isues <= as_of date. This changes it to only return the latest issue <= as_of date

Fix covid hosp as_of to only return latest issue

---

.github/release-drafter.yml
.github/workflows/create-release.yml
.github/workflows/release-helper.yml
src/client/packaging/npm/.gitignore
src/client/packaging/npm/LICENSE
src/client/packaging/npm/README.md
src/client/packaging/npm/package.json
src/client/packaging/pypi/.gitignore

for releasing to pypi and npm + sync dev/main
add a release helper workflow (pipeline) similar to www-main and others. steps taken
* use release-drafter (like www-main) to create release notes and git tag
* publish epidata client to PyPi -> requires `PYPI_API_TOKEN` secret
* publish epidata JS client to NPM -> requires `NPM_TOKEN` secret -> do we have an account?
* create a PR that merges the main back to dev
In addition, small tunings for the definition of the Epidata JS client

ci: add release helper

---

src/acquisition/covidcast/covidcast_meta_cache_updater.py
src/acquisition/covidcast/csv_importer.py
src/acquisition/covidcast/csv_to_database.py
src/acquisition/covidcast/database.py
src/acquisition/covidcast/file_archiver.py
src/acquisition/covidcast/fill_is_latest_issue.py
src/acquisition/covidcast/generate_islatest_fix_sql.py

Change print to structure logging format in the folder `delphi/delphi-epidata/src/acquisition/covidcast`

Covidcast logging

---

docs/api/covidcast-signals/hhs.md

closes 
Add 7dav signals to HHS documentation. Follows the same format and copies the 7dav explanation language from [usafacts](https://github.com/cmu-delphi/delphi-epidata/blob/dev/docs/api/covidcast-signals/usa-facts.md)

Add documentation for 7dav HHS signals

---

docs/api/afhsb.md
docs/api/cdc.md
docs/api/covid_hosp.md
docs/api/covid_hosp_facility.md
docs/api/covid_hosp_facility_lookup.md
docs/api/covidcast_meta.md
docs/api/flusurv.md
docs/api/fluview.md
docs/api/fluview_clinical.md
docs/api/gft.md
docs/api/ght.md
docs/api/nidss_dengue.md
docs/api/nidss_flu.md
docs/api/nowcast.md
docs/api/quidel.md
docs/api/sensors.md
docs/api/twitter.md
docs/api/wiki.md
docs/epidata_development.md
docs/new_endpoint_tutorial.md

closes #578
fixes relative links in the docs to absolute links in the "main" branch

fix relative links in docs to absolute links

---

docs/api/covidcast-signals/fb-survey.md
docs/symptom-survey/coding.md
docs/symptom-survey/collaboration-revision.md
docs/symptom-survey/contingency-tables.md
docs/symptom-survey/data-access.md
docs/symptom-survey/index.md
docs/symptom-survey/modules.md
docs/symptom-survey/problems.md
docs/symptom-survey/server-access.md
docs/symptom-survey/survey-files.md
docs/symptom-survey/survey-utils.R
docs/symptom-survey/weights.md

Change survey name from COVID Symptom Survey to COVID-19 Trends and Impact Survey. Wait to merge until the official name change date, July 9.
- Switch all doc references to use "COVID-19 Trends and Impact Survey".
- Switch docs API menu name from "Symptom Survey" to "COVID-19 Trends and Impact Survey"
- Switch docs survey menu name from "COVID Symptom Survey" to "COVID-19 Trends and Impact Survey"
**Pending** We also need to change the link to FB's data access form once they do the survey name update on their end. Timeline is TBD, so that will happen in a separate PR.

Update docs to refer to survey as COVID Trends and Impact Survey instead of COVID Symptom Survey

---

src/acquisition/covidcast/csv_importer.py
tests/acquisition/covidcast/test_csv_importer.py

change logger.warning to logger.info to avoid error
still need to add/update unit and integration tests to catch this issue in the future

fix logger bug for batch issue upload

---

docs/symptom-survey/contingency-tables.md
docs/symptom-survey/survey-files.md
docs/symptom-survey/weights.md

Fixes links broken due to inappropriately-placed whitespace. Microdata info page was not shown in sidebar after survey name change.
Fixes #626.

Fix broken links in survey docs

---

devops/gunicorn_conf.py

Increases gunicorn's worker timeout to 300s (5min).
It looks like the default of 30s is too short and workers were probably being
killed prematurely. My admittedly somewhat limited testing on a single instance
running a manually edited version of the config file suggests increasing the
timeout will help.

Increase gunicorn timeout

---

src/server/endpoints/covidcast.py

closes the root cause of https://github.com/cmu-delphi/www-covidcast/issues/983
fixes the generation of the new meta data which was buggy for the db alias in the meta lookup
i.e. the reason why chng wasn't part of https://api.covidcast.cmu.edu/epidata/covidcast/meta

fix: lookup of meta data by alias

---

docs/api/covidcast-signals/indicator-combination.md
docs/api/covidcast-signals/jhu-csse.md
docs/api/covidcast-signals/usa-facts.md

7-day-averages of cumulative data are nonsensical. Documents 
* https://github.com/cmu-delphi/covidcast-indicators/issues/1131
* https://github.com/cmu-delphi/covidcast-indicators/pull/1136#

Drop all 7dav cumulative signals from all cases deaths

---

src/server/endpoints/covidcast.py

fix a cornercases in the alias resolver which didn't consider when the source is not about to be returned

fix: handle cornercases where source is not transmitted for aliases

---

docs/symptom-survey/problems.md

Due to a survey sampling error.

Document late July response drop

---

src/acquisition/covidcast/signal_dash_data_generator.py
tests/acquisition/covidcast/test_signal_dash_data_generator.py

Most of this PR is for switching the signals dashboard data generator over to the `covidcast/coverage` endpoint instead of pulling the regional data and counting sizes in a massive groupby. Since `coverage` isn't available natively in the covidcast library (and won't be; that's all going into the new delphi_epidata library/ies) we have to do this by constructing the URL, calling `pandas.read_csv`, and parsing the `time_value` column.
With that change, it makes it less of a big deal to double the length of the coverage time series -- the true goal of this PR.

Signals dash generator: store a longer time series by using covidcast/coverage endpoint

---

requirements.txt
src/server/_params.py
src/server/utils/__init__.py
src/server/utils/dates.py
tests/server/utils/test_dates.py

fixes https://api.covidcast.cmu.edu/epidata/covidcast/?signal=nchs-mortality%3Adeaths_allcause_incidence_prop&geo=state%3Apa&time=week%3A202114-202120 server error
bug was the the index guess logic didn't take weekly signals into account

fix: timepair for week values not working

---

src/acquisition/covidcast/database.py

Additional diagnostic information for 4-hour meta cache update runs the last few days.
We're getting duplicate "thread started" logs for some reason, and the long runtimes seem to be because one of the threads takes ages to finish.
* Log number of threads before we start (to maybe see what is up with duplicates)
* Log after each pair is completed (i tried timing each pair but tests hung -- i suspect time() isn't thread-friendly)

Add pairwise logging for meta

---

src/client/delphi_epidata.py

Add user agent header to async calls

Add header to async calls

---

src/server/_pandas.py
src/server/_query.py
tests/server/test_pandas.py

Addresses this comment https://github.com/cmu-delphi/delphi-epidata/pull/646#issuecomment-889457081.
Currently, the `/correlations` endpoint in covidcast bypasses the row limits requirements by passing the query directly to `pd.read_sql_query`. This PR abstracts row limiting from `run_query` and adds it to `as_pandas`. A test to make sure it works is provided. 
There may be a possible issue where someone requests too many rows and the row limit leads to the two correlated time series being mismatched, which would likely lead to an Exception later in the correlation code. We could try and send an error message if the number of returned rows == MAX_RESULTS instead of proceeding, getting an error, and sending nothing.

Limit rows returned for correlations

---

.github/workflows/missing_signals.yaml
.gitignore
scripts/report_missing_covidcast_meta.py

add a script and github action helper workflow to detect discrepancies between covidcast_meta and covidcast/meta, i.e. missing signals in the google sheet. will generate a file like this:
[missing_db_signals.csv](https://github.com/cmu-delphi/delphi-epidata/files/7203996/missing_db_signals.csv)

Add a missing signal detector helper job

---

docs/symptom-survey/problems.md

Follow-up to https://github.com/cmu-delphi/covidcast-indicators/pull/1072.

Document item B13 being missing from microdata for a while

---

integrations/acquisition/covidcast/test_csv_uploading.py
src/acquisition/covidcast/csv_importer.py
tests/acquisition/covidcast/test_csv_importer.py

Closes #731
* repair and log instead of rejecting files with invalid missing codes
* introduce dtype inference code in acquisition to see if further refactors possible (see [this comment](https://github.com/cmu-delphi/delphi-epidata/pull/730#discussion_r721686153))
* refactor test_csv_uploading for readability

Repair and log nancodes instead of rejecting files

---

docs/api/covidcast-signals/chng.md

closes #774 
Adds documentation for chng flu signal.
Not sure if the Earliest date available field is correct. If we start today with a backfill of 60 days, we'll be right around 10/1. We obviously could do a special run that creates a signal going back to 2020-02-01 if we wanted to though.

Add chng flu docs

---

docs/api/covidcast-signals/fb-survey.md

Correct formulas so that they match the code.
Accompanies [#1065](https://github.com/cmu-delphi/covidcast-indicators/pull/1065).

Update formulas for weighted count and binary indicators

---

docs/api/covidcast-signals/quidel.md

closes [#807](https://github.com/cmu-delphi/delphi-epidata/issues/807)
Add more detailed description to the available threshold for Quidel Covidtest signals.
For raw signals, we only report counts larger than or equal to 50.
For smoothed signals, 
- when count is smaller than 50 but larger than or equal to 25, we conduct the geographical pooling strategy; 
- when count is smaller than 25, we report nothing

fix the description of the availability threshold

---

docs/api/covidcast-signals/google-symptoms.md

closes 
Updated documentation for Google symptoms signals.

documentation for google symptoms new signals

---

docs/symptom-survey/coding.md

The main sample (85%) is now receiving Wave 13, not the reverse.
Fix Wave 13 changelog deployment description. It'd be good to get this correction out quickly, if we can deploy the doc update.

Correct Wave 13 overlap description

---

docs/api/covidcast-signals/dsew-cpr.md

Document CPR indicator with hospital admissions signal.

Add documentation for new Community Profile Report indicator

---

docs/api/covid_hosp.md
docs/api/covid_hosp_facility.md
docs/api/covid_hosp_facility_lookup.md
docs/api/covidcast-signals/hhs.md

closes #827 
The COVID-19 Patient Impact and Hospital Capacity datasets from HHS are in the public domain as works of the US Government, not ODBL.

Correct license for data from HHS

---

.github/workflows/ci.yaml

Uploads images built during `build` job as a workflow artifact, then downloads them during `run_tests` in order to start the necessary services for ci testing.
Unblocks `image` job from depending on successful `build` incl passing tests.

Split CI tests to a separate job from build

---

docs/api/covidcast_signals.md

closes #799 
Switch to new category schema, remove old signals, add new ones. Also switch to new endpoint-based instead of API-based language, long overdue.

Correct COVIDcast dashboard signal list

---

requirements.txt

`itsdangerous` released version 2.1 today, which removed the `json` submodule. `itsdangerous.json` is used by our version of Flask, so its removal causes the web server to crash.
This PR pins `itsdangerous` to just before 2.1, so that `itsdangerous.json` is still available.
Eventually we should address #848 properly, likely by upgrading Flask, but this PR is the shortest distance to a successful build.

temporary patch for failing build due to Flask->itsdangerous->json 

---

src/server/endpoints/covidcast_utils/model.py

closes #841 
Just adds 'r' to the `re.compile` line.

Add regex decorator to re string

---

requirements.txt
src/server/_logger.py
src/server/_query.py
src/server/_security.py
src/server/main.py

This PR implements API key scrubbing for logs in the application layer (Flask + gunicorn). If the user is authorized and tracked, the API key will be logged whenever the user makes an API request. If the user is not tracked, the API key parameter will be masked / scrubbed out. 
For logs in the web server layer (NGINX), the API key will be shown as a query string during client requests. This will need to be filtered by creating a custom filter or ingestion pipeline on Filebeat before ingesting to Elasticsearch.
- Create an ingestion pipeline / filter in Filebeat to scrub the "api_key" query string from the incoming NGINX logs.
- Make Flask logs more useful (analytics-friendly) for Kibana by adding more parameters such as list of COVIDcast data sources, etc.

Implement API key scrubbing and structured logging

---

src/acquisition/covidcast/csv_importer.py
tests/acquisition/covidcast/test_csv_importer.py

Part of fixing https://github.com/cmu-delphi/covidcast-indicators/issues/1520. This should be merged first, as it will be a no-op (aside from a memory usage increase on the acquisition server). Then we can merge the archivediffer fix (upcoming).
Allows NAs in missing columns, so the validation can fix them. This will allow archive differ to easily add deletion codes, not have to do any validation on the rest of the missing codes, and let the validation here in acquisition take care of it.

Allow NAs in missing columns

---

src/acquisition/covidcast/database.py
src/acquisition/covidcast/delete_batch.py

While testing quidel deletions in staging, it became clear that we missed a few things in review...
* add missing rowcount handling to `database.py:Database.delete_batch()`
* add missing rowcount-unsupported logic to `delete_batch.py:main()`
* add missing imports to `delete_batch.py`
* add missing argument to `delete_batch.py:handle_file()`
* add missing `time_type` logic to `delete_batch.py:handle_file()`
* add missing arguments to `handle_file()` call in `delete_batch.py:main()`

Fix bugs identified in staging tests

---

src/acquisition/covidcast/database.py

If you try to `INSERT INTO ... VALUES` with too many items, the MySQL server "goes away" and crashes the next query. "Too many" is somewhere between 100k and 400k: 100k runs, 400k does not. There are ways to address this in client and server settings, but to be less invasive, this PR splits the `VALUES` into 100k chunks.

Split large deletion batches into smaller chunks

---

integrations/server/test_covidcast_meta.py

test_covidcast_meta used to depend on prior tests to set secrets.db.host instead of setting them itself, creating an ordering dependency. By setting secrets in each test in which they are used, we remove the ordering dependency and ensure tests pass regardless of whether they're run alone or as part of a suite.

Set test secrets in test_covidcast_meta

---

docs/symptom-survey/coding.md

Wave 13 V2d incorrectly referred to as V2a

[CTIS] Wave 13 V2d incorrectly referred to as V2a

---

requirements.txt

Jinja is a dependency of Flask. In Jinga 3.1.0, `escape` is deprecated and should be imported from MarkupSafe. We can pin `jinja<3.1.0` to work around this for now.
Probably the better fix will be to update Flask, but since we are already pinning it to an older version it seems likely that we can't do this easily.

Fix Flask Jinja dependency

---

dev/local/epidata-refresh.sh
dev/local/install.sh
docs/epidata_development.md

Installation script ensures nothing but code winds up in the resulting Docker images.
Refresh script automatically keeps track of what's running, shutdown/build/run procedures, and test bindmounts. We've got people copy-pasting whole paragraphs of shell commands and losing track of which copypastes do what, and that's just not necessary.

Local dev scripts: installation, docker refresh

---

README.md

Move quickstart up further for maximum obviousness

---

docs/api/covidcast-signals/chng.md
docs/api/covidcast-signals/doctor-visits.md
docs/api/covidcast-signals/dsew-cpr.md
docs/api/covidcast-signals/google-symptoms.md
docs/api/covidcast-signals/hhs.md
docs/api/covidcast-signals/hospital-admissions.md
docs/api/covidcast-signals/jhu-csse.md
docs/api/covidcast-signals/nchs-mortality.md
docs/api/covidcast-signals/usa-facts.md

Issue: The CHNG documentation (and documentation for any other source with suppressed sample size) should document that the sample_size column is left deliberately blank, and provide reasons.
Fixes:
1. add the reason of "Standard errors and sample sizes are not available/applicable for this data source/metrics." in all there pages limitation sections.

#910 CHNG-documentation

---

README.md
docs/epidata_development.md

Puts our new dev quickstart recipes and tools in the main README, where developers are more likely to find them.
Should I merge this into `main` as a docs hotfix?

Update `README.md` with dev quickstart recipes

---

dev/local/Makefile
src/acquisition/covidcast/covidcast_meta_cache_updater.py
src/acquisition/covidcast/csv_to_database.py
src/acquisition/covidcast/database.py
src/ddl/migrations/v4_renaming.sql
src/ddl/v4_schema.sql

4 commits, each for:
- [cli option for specifying # of metadata worker threads](https://github.com/cmu-delphi/delphi-epidata/commit/0d4188b95bde9c4e162c7ec902b7c6c0ff9f569e)
- [added flag to Makefile for new percona db image (and some whitespace fixes)](https://github.com/cmu-delphi/delphi-epidata/commit/5e3eb51c005720a9da1e52ee78fb1cbfc0339516)
- [converted JOINs in VIEWs to 'USING' instead of 'ON'](https://github.com/cmu-delphi/delphi-epidata/commit/b9ab3f3fe09fb6c015baece120e68fa591c06a4b)
- [added ANALYZE TABLE to the end of acquisition runs (and some whitespace fixes)](https://github.com/cmu-delphi/delphi-epidata/commit/a61a5db5b830cc6c0c124c6ee3374264970c1976)

Metadata threads and ANALYZE and etc

---

integrations/acquisition/covidcast/test_db.py
src/acquisition/covidcast/csv_to_database.py
src/acquisition/covidcast/database.py
tests/acquisition/covidcast/test_database.py

addresses #941
a question remains about how to handle the new exception in `csv_to_database.py:upload_archive` -- i would argue the behavior i have here is correct: it stops processing any more files and leaves them where they are.  the exception condition would arise because of a problem with the database (and not with the files) so it should not handle unprocessed files with `archive_as_failed`.  if this breaks some filesystem maintenance paradigm though, im fine with changing it.

DBLoadStateException: halt acquisition when unexpected data found in load table

---

dev/local/Makefile

* to be optimally kind to the web server, the db server really ought to come up first
* added virtual network setup to db target as well as web target so it works in either order

Change default dependency order in local dev

---

.github/workflows/ci.yaml
devops/Dockerfile
requirements.txt
src/server/_config.py
src/server/_query.py

TEST - Build and image with new Flask and SQLAlchemy

---

dev/local/Makefile
package-lock.json

closes 
Because we updated MYSQL version, the line we search in the logs to detect that the DB is ready has changed. So change it in the Makefile here.

Fix Makefile grep command and package-lock.json

---

src/server/_query.py
src/server/utils/__init__.py
src/server/utils/dates.py
tests/server/test_query.py
tests/server/utils/test_dates.py

Closes #790.
Currently, the API works with mixed lists of dates and date ranges for date-based filtering, e.g.:
```
[20200101, 20200102, (20200101, 20200104), 20200106, 20200107, 20200108]
```
This PR adds a utility function, `dates_to_ranges`, to optimize those lists, grouping consecutive dates into ranges (which in SQL are represented by a single `BETWEEN` filter rather than multiple `OR` filters) and removing duplicate dates.
e.g., after the function is applied, the mixed list above becomes:
```
[(20200101, 20200104), (20200106, 20200108)]
```
The first two values from the original list are merged into a range, and so are the last three.

Use BETWEEN queries in the API as much as possible

---

src/server/_query.py
src/server/utils/__init__.py
src/server/utils/dates.py
tests/server/test_query.py
tests/server/utils/test_dates.py

A followup PR to https://github.com/cmu-delphi/delphi-epidata/pull/977, this makes a few changes to the new datetime optimization code:
- merges `days_to_ranges` and `weeks_to_ranges` into a single `_to_ranges` function with `Callable` arguments
- adds extra tests for some edge cases, as well as `TimePair` objects
- other minor changes

Tweaks to datetime optimization

---

docs/api/covid_hosp.md
docs/api/covid_hosp_facility.md
docs/api/covid_hosp_facility_lookup.md

* describe forward-fill and annual reporting limitations
* link to HHS FAQ, which has better information on all fields
* correct the output documentation for facility lookup

Update covid_hosp endpoint documentation with August 2022 limitations

---

devops/gunicorn_conf.py

Our query time has increased. This PR increases how long Gunicorn will wait
before deciding to terminate client connections.
Increases Gunicorn's timeout parameter.

Increase Gunicorn's idle timeout

---

requirements.txt
src/server/_params.py
src/server/_query.py
src/server/_validate.py
src/server/endpoints/covidcast.py
src/server/utils/__init__.py
src/server/utils/dates.py
tests/server/test_params.py
tests/server/test_query.py
tests/server/utils/test_dates.py

Closes #999.
Refactors several parts of the datetime code as specified in #999. Specifically:

Code improvements to time processing routines

---

src/server/endpoints/covidcast.py

`request.args` is just for GET variables, `request.values` combines GET and POST variables.  `values` is used everywhere else, this gets rid of the only `args` usage.

use request.values instead of request.args

---

dev/local/Makefile

Adds two targets useful for debugging:
* `mysql` - a live mysql prompt to the dev database
* `bash` - a live bash prompt in the python environment

Add live debugging targets to local dev Makefile

---

src/server/_printer.py

Small accident, quick fix. Likely gets caught somewhere else anyway, but better to be explicit.
An exception variable got unbound, even though it is used.

Server: fix unbound exception variable

---

src/server/_params.py
src/server/_query.py
src/server/endpoints/covidcast.py
src/server/endpoints/covidcast_utils/model.py
tests/server/endpoints/test_covidcast.py
tests/server/test_params.py
tests/server/test_query.py

Partially addresses #998.
Fixes a set of issues in the server code as described [here](https://github.com/cmu-delphi/delphi-epidata/issues/998#issuecomment-1348732544).

API server code health pass - rename *Pair classes to *Set

---

src/acquisition/covid_hosp/common/database.py
src/acquisition/covid_hosp/common/utils.py
src/acquisition/covid_hosp/facility/database.py
src/acquisition/covid_hosp/state_daily/database.py
src/acquisition/covid_hosp/state_timeseries/database.py
src/ddl/covid_hosp.sql
src/ddl/migrations/covid_hosp_meta_v0.4.4-v0.4.5.sql
tests/acquisition/covid_hosp/common/test_database.py
tests/acquisition/covid_hosp/common/test_utils.py

Prevents future recurrence of the HHS state hospital admissions outage active 2023-01-12.
In January 2023, we noticed that the HHS hospital admissions data had unusually high lag. On investigation, it turned out that timeseries datasets had not been fetched in over a week, even though new timeseries revisions were available from healthdata.gov. It turned out that successful import of daily revisions (which in Jan 2023 have 7 days of lag, while timeseries revisions have only 1-2) were masking the new timeseries revisions from the acquisition system.
This PR changes the usage of the `dataset_name` column in the `covid_hosp_meta` table from containing the data table name (for which `covid_hosp_state_timeseries` is shared by both the timeseries and daily revisions …

Fix problem with covid_hosp skipping state revisions.

---

src/acquisition/covidcast/csv_importer.py
tests/acquisition/covidcast/test_csv_importer.py
tests/acquisition/covidcast/test_csv_to_database.py

A few small refactors for clarity that I couldn't help myself in making while working on #947.
Most of the changes are purely for better readability. No functionality is altered, except for the interface of `load_csv`, but this should not affect actual usage.
* rename RowValues to CsvRowValue
* make CsvRowValue into a dataclass
* remove `pandas` optional argument from `load_csv` that was only used for test mocks
* use `unittest.patch` to mock test instead
* update other tests
* update `csv_to_database` with a few relative imports
I changed 
```py
def load_csv(filepath, geo_type, pandas=pandas):
def load_csv(filepath, geo_type):
```
where `pandas` was just an abstract argument to the Pandas library meant for mocking. Instead of complicating this function's interface, we can just use …

[Refactor] Clarify a few `csv_importer` types and names

---

src/acquisition/covidcast/csv_importer.py
src/acquisition/covidcast/csv_to_database.py
src/acquisition/covidcast_nowcast/load_sensors.py
tests/acquisition/covidcast/test_csv_importer.py
tests/acquisition/covidcast/test_csv_to_database.py
tests/acquisition/covidcast_nowcast/test_load_sensors.py

A follow up to #949. There were just some pieces of this code that really bothered me cause they were unnecessarily confusing to read every time I went there.
- Remove a bunch of unnecessary function arguments by correctly patching in tests
- Add type hints to many functions
- Simplify the logic that returns a list of CovidcastRows for database import
- Convert the path details tuple to a NamedTuples, so it's less of a mystery

[Refactor] Further cleans of `csv_importer` 

---

dev/local/Makefile

Adds a configuration option to the Makefile to make it able to build with a different database set as target. Needed for the scaling test rig to make run off of a database other than a locally created one.

Add SQL override to Makefile

---

dev/local/Makefile

Due to [package incompatibility](https://github.com/Toblerity/Fiona/discussions/1071), this PR adjusts the Makefile to build and run affected containers using linux/amd64 by default.
Local make all and make tests has no error and takes around 50s on my M1 macbook.

Fix packages incompatibility with Apple M1 by defaulting to linux/amd64 containers

---

.github/workflows/performance-tests.yml

Updates perftests workflow port from 8080 to 10080.

Update performance testing workflow port

---

integrations/server/test_covidcast.py
src/client/delphi_epidata.py

- Use epidata client in covidcast integration tests 
- fix format = csv bug 
- fix fields param bug
fix #67

Use epidata client in covidcast integration tests + fix csv format bug + fix fields param bug

---

src/server/endpoints/covidcast_utils/model.py

This is a variant of #1026.
Create an early exit from the JIT iterator stack for non-derived signals. The advantage of this approach is that it still relies on a single database query, instead of making multiple, like #1026.

[JIT Variant]: Reduce iterator stack on base signals

---

deploy.json

Fixes failing Deploy Repo job in Automation
Our home-brewed deployment system requires handling directories and subdirectories one at a time (there's no recursive traversal afaict). Looks like we added a dependency at some point recently where the tests reach into epidata.server.utils, but the utils directory was never added to deploy.json so the tests couldn't find the utils code at deployment time. This caused deployments to fail:
```
Traceback (most recent call last):
File "/home/automation/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/automation/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
exec(code, run_globals)
File …
```

Add server.utils to deployment config

---

.github/workflows/performance-tests.yml

Updates the performance testing rig to make its PR comment output a summary of the run, which looks like this:

Enhanced output for performance testing rig

---

src/acquisition/covid_hosp/common/utils.py

aka "fixin' 2: electric boogaloo"
a follow-up to #1083, as we are still seeing very long running time for `covid_hosp_facility` acquisition in production.

covid_hosp update running time improvements -- part 2

---

integrations/client/test_delphi_epidata.py
src/server/_params.py
tests/server/test_params.py

but it does know about "state_id", "state_code", and "state_name" (see [delphi_utils/geomap.py](https://github.com/cmu-delphi/covidcast-indicators/blob/2f92ca7ecf88c715bf152bd23e256e22347c50ae/_delphi_utils_python/delphi_utils/geomap.py#L545-L546)).  "state_id" appears to be the two-digit state abbreviation, if [delphi_utils/data/2020/state_pop.csv](https://github.com/cmu-delphi/covidcast-indicators/blob/main/_delphi_utils_python/delphi_utils/data/2020/state_pop.csv) is to be believed.
this is untested!  i whipped it up fast to address the issue we saw post-rollout.  its kinda hacky and i dont love the ternary form of it.  ...but it should do the trick, at least in prod for now.
obviously, it should be accompanied by some new additional unit and/or integration tests that involve a "state" …

get_geo_values() doesnt know about a plain "state" type

---

src/acquisition/covidcast/csv_importer.py
tests/acquisition/covidcast/test_csv_importer.py

Updates #1103 
I meant to make only a few specific changes, but I ended up making a lot of changes.
* `pandas.DataFrame.apply` is just a Python for-loop under the hood, which is slow, so I rewrote these methods to use the built-ins, which rely on fast numpy functions
* we don't need to fall back to `str` dtypes in the Pandas dataframe: it complicates code downstream, makes the code slower (because of redundant dtype casting), and, based on my log-digging in [this thread](https://delphi-org.slack.com/archives/C013AH5N01E/p1680210412446129), the code path hasn't occurred in over a year (and only then occurred once due to a bug which was fixed with a data type change)
* fixed/updated a few exception handlings: 
* ValueError in the first exception in load_csv made the …

Refactor csv_importer.py with Pandas

---

requirements.api.txt
requirements.dev.txt

i assumed this was not version-pinned and would use whatever was most up to date.  i shoulda checked!  fwiw, we were pinned to a version from august 2022.
this should pick up the change from https://github.com/cmu-delphi/covidcast-indicators/pull/1835

update delphi_utils version

---

dev/docker/python/Dockerfile
dev/local/Makefile
integrations/client/test_delphi_epidata.R
src/client/delphi_epidata.R
src/client/delphi_epidata.py

* bring py client in line with current api key behavior (permit anonymous requests, handle 401 and 429)
* support api keys in r client
- add integration test for r client
- add R to python image (double checked this image only used for local dev and github ci)
- add `r-test` local development target (i didn't add it to ci but i could if folks think it's needed)
* minor improvement to error handling in py client that's been bugging me for months if not years - if json was expected but can't be parsed, show the user the actual error message from the server instead of the json parsing exception

API Keys: Clients

---

docs/api/README.md
docs/api/api_keys.md
docs/api/covidcast.md
docs/api/privacy_statement.md
docs/epidata_development.md
docs/index.md
docs/new_endpoint_tutorial.md
docs/symptom-survey/index.md

Partially addresses AK-59
Draft mode until we know what the rate limit is
[Rendered preview here](https://krivard.github.io/delphi-epidata/api/privacy_statement.html)
API Keys comms:
* Home page
* API Keys overview page, including usage instructions
* I included this as a sidebar header just after the home page, so all the other toplevel pages got bumped down
* Privacy statement

API Keys: Documentation

---

docs/api/README.md
docs/api/api_keys.md
docs/api/covidcast.md
docs/api/privacy_statement.md
docs/epidata_development.md
docs/index.md
docs/new_endpoint_tutorial.md
docs/symptom-survey/index.md

all of the documentation changes to the `api-keys` branch appear to have been made #1158, this yanks them into the `dev` branch too.

importing `api-keys` Documentation

---

docs/api/api_keys.md
docs/index.md

Final (?) sync with comms doc.

Last-minute docs changes

---

src/server/_common.py
src/server/_security.py

to remove unnecessary query to db

dont look up user if no api key is given

---

src/server/_common.py
src/server/_config.py

configuration and handling to prevent potential ip address spoofing when behind certain kinds of proxies.
see loquacious comments inside the PR for more details.

properly handle and interpret X-Forwarded-For header

---

src/server/admin/models.py

defaults for date columns `last_time_used` and `created` in the `User` table were statically set to whenever that code was first evaluated.  this makes them dynamic.

fix defaults for time columns in user table (with orm)

---

docs/api/api_keys.md
docs/api/client_libraries.md

[Karla's question](https://github.com/cmu-delphi/delphi-epidata/issues/1183#issuecomment-1584723472) revealed that we don't have API key usage instructions for clients linked from the API Keys usage page. This PR fixes that. 
Changelog:
* api_keys.md: Link to client documentation for API key usage
* client_libraries.md: Describe API key usage for one-file clients; add links to new epidat* clients

Link to client instructions from API Keys Usage section

---

src/server/_config.py
src/server/endpoints/admin.py

(...and also some cleanup in admin endpoint file)
turns out...  the default value for `PROXY_DEPTH` set in https://github.com/cmu-delphi/delphi-epidata/pull/1191 is not high enough for the CC API servers and is likely not high enough for the AWS API servers.  iirc, the old value of "2" came from some testing on the staging setup, which is apparently not close enough to the configuration of either of the prod setups.
this change updates the value to match CC, which should be sufficient for AWS.  this change also adds a new endpoint (`api.delphi/epidata/admin/diagnostics`) which gives more visibility into the proxy chain of a running system (and maybe other things in the future).  it is only accessible with an admin token.

update/fix PROXY_DEPTH default value, add 'diagnostics' endpoint

---

src/server/_common.py
src/server/_db.py
src/server/_security.py
src/server/admin/models.py
src/server/endpoints/admin.py
src/server/main.py

change 'user_engine' to a 'WriteSession' instead, so the master db connection is used for writes only

use second db handle for only for user admin and writes

---

src/server/_security.py

re-enable tracking of last time an api key was used

---

src/ddl/fluview.sql
src/ddl/migrations/fluview_clinical_v0.1.sql

Add new UNIQUE CONSTRAINT on `fluview_clinical` table. Remove duplicate records from `fluview_clinical` table.

Remove duplicates from `fluview_clinical` table

---

src/common/covidcast_row.py
src/common/logger.py
tests/acquisition/covidcast_nowcast/test_load_sensors.py
tests/acquisition/flusurv/test_flusurv.py
tests/acquisition/flusurv/test_flusurv_update.py
tests/acquisition/fluview/test_impute_missing_values.py
tests/client/test_delphi_epidata.py
tests/common/test_covidcast_row.py

Part of #962 
- Runs the tests and a few `common` dir files through black
- Holds off on `covid_hosp` and `covidcast` until the PRs on those are merged

style(tests): format many tests with black

---

src/server/_printer.py
src/server/endpoints/covidcast_meta.py

allow and enable HTTP caching of metadata endpoint via "Cache-Control" header++
see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
this means clients dont have to keep making requests for the metadata when its not going to change.
[the R lib doesnt seem to consider the "Age" header](https://github.com/r-lib/httr/blob/HEAD/R/cache.R), but appears it will use the date instead, so it might sometimes use metadata that might be a smidge stale which shouldnt be a big deal.

http caching for metadata

---

src/server/_common.py
src/server/_config.py
src/server/_limiter.py
src/server/_printer.py
src/server/_security.py

Dropped phase handling for API keys

Drop phase handling

---

src/server/utils/dates.py

closes https://github.com/cmu-delphi/delphi-epidata/issues/1038
set `logger.debug` in `dates.py`

setted `logger.debug` in `dates.py`

---

src/client/delphi_epidata.py
src/client/packaging/pypi/delphi_epidata/__init__.py

Part of #962
- Run delphi_epidata.py through black and flynt
- Recommend "hide whitespace" setting for viewing diffs

style(client): run py client through black

---

src/server/_limiter.py

Fixed dashboard signals parsing for dashboard queries.
Used parse_source_signal_sets() function to parse (source, signal) pairs

Fix dashboard signals parsing for dashboard queries

---

deploy.json

hopefully this works to make `github-deploy-repo` catch all the files from `src/common/` (#1203 added a file to `src/common/covid_hosp/`, and there are a total of 3 in that subdir now)

followup for #1203: deploy.json fix for src/common/*

---

src/acquisition/covidcast/database.py

Fixex sorting in compute_covidcast_meta
Added missing `api_user` creation in integrations/acquisition/covidcast/

Fix sorting in compute_covidcast_meta

---

deploy.json

Tell github-deploy-repo to copy new maintenance dir and files.

Add deployment config for maintenance dir and files

---

src/common/logger.py

- bringing the `logger.py` files from https://github.com/cmu-delphi/delphi-epidata/ and https://github.com/cmu-delphi/covidcast-indicators/ back in sync.  (there will be equivalent PRs in both repositories.)
- larger functional differences are now applied to both:
- the version in `covidcast-indicators` didnt log PIDs 
- nor did it have the env var trick to get debug-level output
- the version in `delphi-epidata` didnt always respect output filenames properly (though it seems we didnt actually trigger this in practice; look at the collapsible section below for how to see this for yourself).
- differentiated the uncaught exception handlers a bit
- and reduced the log level for messages from threads exiting cleanly.  this is mostly because multiprocessing.Manager processes start and [stop …

bring loggers in sync and add multiproc capabilities

---

docs/api/covidcast.md

add syntax feature documentation

---

src/server/endpoints/covidcast_utils/descriptions.raw.txt

Syncing covidcast_utils files to www-covidcast release v3.2.7.

Sync to www-covidcast release v3.2.7

---

docs/api/covidcast-signals/quidel-inactive.md
docs/api/covidcast-signals/quidel.md
docs/api/covidcast_signals.md
integrations/server/test_covidcast_endpoints.py
integrations/server/test_covidcast_meta.py
src/server/_security.py
src/server/endpoints/covidcast.py
src/server/endpoints/covidcast_meta.py

moving quidel signals to non-public access
includes:
- small updates to documentation
- removal of reference to and usage of quidel signal in covidcast dashboard
- specification of restricted signal "source(s)" and which role(s) can access them
- signals w/ restricted sources are silently ignored when requested in covidcast endpoint (unless user is authorized)
- signals w/ restricted sources are omitted from metadata results (unless user is authorized)
still needs:
- automated integration tests
- plan for longer term permission model format/storage
- may want to address signal source name aliasing
- decision can probably be delayed temporarily
- unsure if these are at their final file locations:
- `sources_protected_by_roles` (in src/server/_security.py now)
- `restrict_by_roles` (in …

moving quidel signals to non-public access

---

src/server/endpoints/covidcast.py

follow-up to #1261, applies the same protections to `covidcast/csv` and `covidcast/backfill` as were already done to the other similar endpoint routes.
not sure how i missed these before (they dont use the same pattern for getting the requested source+signal as the other endpoint routes do, but thats not an excuse)

adding protected signal coverage for endpoints previously missed

---

src/server/_params.py
tests/server/test_params.py

Fixed ISO range parsing for /covidcast endpoint

Fix ISO range parsing

---

integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py

whoops, i wasnt paying attention on the command line and my commit message got slightly mangled, it should read:
"revert `async_epidata()` to previous behavior, and mark deprecated (`filterwarnings()` not fully tested)"
to be added to #1288 
i did not do much testing around the `warnings.filterwarnings()` call, but it is intended to print the deprecation warning for the method only once (on its first use), no matter how `async_epidata()` is called.

revert and deprecate async_epidata (+ Remove usage of PHP alias in the Python client)

---

integrations/client/test_delphi_epidata.py
src/server/_params.py

Made as_of query to fail with a helpful error message if len(as_of) > 10

Fix `as_of` for date range

---

src/server/endpoints/covidcast_utils/model.py

Pass only reflexively valid fields to the `DataSignal` constructor when loading from `db_signals.csv`, instead of using a rigid and brittle set of fields (columns) to exclude.  The system will now easily ignore new columns added to the CSV file, but for which it doesn't yet have a use.  This will make it effortlessly handle changes coming in #1259 (and beyond).
I considered logging a list of unused fields/columns, but that will already be noisy because of the existing `base_is_other` column, and i dont think itll be very helpful.

Make DataSignal construction more flexible

---

.github/workflows/performance-tests.yml

Adds an extra step to the performance test runner which cleans up further files from previous (now self-hosted) runs.

Cleanup more files from previous runs of performance test rig 

---

integrations/server/test_covidcast.py
src/server/_params.py

It looks like #1284 broke some week and week range parsing and was noticed in https://github.com/cmu-delphi/covidcast-indicators/issues/1904.
Heres evidence of the new test failing before i applied the fix:
https://github.com/cmu-delphi/delphi-epidata/actions/runs/6564148018/job/17829935532
This solution is a bit brittle, but ~all of `_params.py` is a mess and needs to be cleaned up, so i think this can fly for now.

Fix week parsing for date parameters/arguments

---

.github/workflows/performance-tests-one-time.yml

Adds a one-time testing workflow that will periodically run the performance scaling test rig and see how the results stack up. This is set to run every 30 minutes on October 25th, and can be safely deleted/reverted afterwards. Similar to #1253.

Add one-time performance testing workflow

---

src/client/delphi_epidata.py

Closes #1320.
Appends a trailing slash to URLs requested by the Python client, which should prevent an automatic redirect and an extra request to the server.

Prevent "308 PERMANENT REDIRECT" via client change

---

integrations/server/test_api_keys.py
src/server/endpoints/covidcast_utils/dashboard_signals.py
src/server/endpoints/covidcast_utils/descriptions.raw.txt

* preemptively adds `nchs-mortality:deaths_covid_incidence_prop` into the ratelimit-exempt signal set
* changes hospital admissions override signal for county-level visualizations to an active/current signal (from a `dsew-cpr` to `hospital-admissions:smoothed_adj_covid19_from_claims`)
* adds a fix to include override signals in the ratelimit-exempt set
* fixes tests to work around changes to exemption status of above signals

changes to signals in rate-limit exempt list

---

.github/workflows/performance-tests-one-time.yml
.github/workflows/performance-tests.yml

Adds a Delphi API key to be used in the Locust `v4.py` file. It is added as a header, so should not show up in Locust logs. Also modifies the one-time workflow so that it runs again after this PR is merged.

Add API key from secrets

---

src/acquisition/covid_hosp/common/database.py
tests/acquisition/covid_hosp/common/test_database.py

The change from #1224 does not work on production, presumably because of the new superlong INSERT INTO...UPDATE statement that it introduced.  With it, [this `executemany()` call](https://github.com/cmu-delphi/delphi-epidata/blob/bc7e37590d22c541d87430684e12c747b71c6fd0/src/acquisition/covid_hosp/common/database.py#L214) hangs indefinitely and pegs the CPU (this even happens with a batch size of 2).  The covid_hosp tables have [a large number of lengthy column names](https://github.com/cmu-delphi/delphi-epidata/blob/bc7e37590d22c541d87430684e12c747b71c6fd0/src/ddl/covid_hosp.sql#L380-L500), and each gets repeated thrice in the INSERT INTO...UPDATE syntax, making for a ~20k character long SQL statement (and this doesn't even consider the literal values that get inserted).  It stands to …

use REPLACE INTO instead of INSERT INTO...UPDATE in covid_hosp acquisition

---

src/client/delphi_epidata.py

Closes #1301.
Removes uses of setuptools' deprecated `pkg_resources` library - these are replaced by the native `importlib.metadata` library.

Replace deprecated pkg_resources

---

.gitignore
docs/api/covidcast-signals/fb-survey.md

Moving fb_survey source into inactive folder

---

dev/local/setup.cfg
integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py

Closes #1321.
Adds two debug modes to the Python client library **(JS and R clients TBD)**:
- `debug` logs info about HTTP requests and responses.
- `sandbox` prevents any HTTP requests from actually executing, allowing users to test a long-running or expensive script without any actual server load.

Add inspection modes to Python client library

---

docs/api/flusurv.md
src/acquisition/flusurv/flusurv_update.py
src/ddl/fluview.sql
src/ddl/migrations/flusurv_age_sex_race_strata.sql
src/server/endpoints/flusurv.py

Update `flusurv` table schema to support #1278. Also make sure `rate_age_5`, `6`, and `7` are returned.
Necessary for https://github.com/cmu-delphi/delphi-epidata/issues/1247

Update flusurv schema and docs with new age, sex, and race groups

---

src/server/_common.py
tests/server/test_validate.py

Related: #1386.
Logs the HTTP Referer (or referrer) header as `req_referrer` and Origin header as `req_origin`, helping us track where requests come from. The easiest way to test this is via Postman:
This generates the following log string:
```
{"method": "GET", "url": "http://localhost:10080/epidata/signal_dashboard_status/", "form_args": {}, "req_length": null, "remote_addr": "172.18.0.1", "real_remote_addr": "172.18.0.1", "user_agent": "PostmanRuntime/7.30.1", "api_key": null, "user_id": "None", "req_referrer": "https://test.com/test", "event": "Received API request", "logger": "server_api", "level": "info", "pid": 8, "timestamp": "2024-05-09T11:28:19.206454Z"}
```
```
{ ... "req_referrer": "https://test.com/test" ... }
```
An automated version of this test has also been included. If …

Log HTTP referer and origin

---

src/client/packaging/pypi/CHANGELOG.md
src/client/packaging/pypi/setup.py

Closes #1432.
Updates the Python client's changelog to include items from previous releases.
Also includes a few currently pending changes. These can be omitted if we want to update the CHANGELOG right away; otherwise the date will need to be updated during the next release.

Update Python client CHANGELOG

---

docs/api/client_libraries.md

Addresses https://delphi-org.slack.com/archives/C028AUR6MV1/p1706908159673089?thread_ts=1706903688.300809&cid=C028AUR6MV1
Say `epidatr` package is done and link to CRAN page. Add example use and de-emphasize legacy R use.

Highlight epidatr readiness

---

requirements.api.txt
requirements.dev.txt
src/client/delphi_epidata.py
src/client/packaging/pypi/CHANGELOG.md
src/client/packaging/pypi/setup.py

* add delphi-utils as dependency to Python client
* import logger from delphi-utils instead of locally
* unpin delphi-utils in both requirements files

fix: Python client logger import

---

src/server/admin/api_key_form_script.js

This just updates our repo's copy of the js file, the running Google Apps Script has already been modified.

Add mailing list info to API key registration email

---

docs/index.md

Updated Epidata Index page to focus less on Covidcast and Covid-19.

Updated Epidata Index (main description page)

---

integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py
src/client/packaging/pypi/pyproject.toml

This drops the requirement for the bloated `delphi_utils` package in the python client, and replaces the `delphi_utils.logger` with printing to STDERR instead.
Addresses #1467 
I havent tested this yet, and i imagine it is going to fail CI.

py client: drop delphi_utils requirement, log to stderr instead

---

docs/api/covidcast-signals/hhs.md

Move hhs docs under inactive signals

Put hhs docs under inactive signals

---

integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py

Changes from [this comment](https://github.com/cmu-delphi/delphi-epidata/pull/1497#pullrequestreview-2188960180).

fix: simplify client version check

---

.github/workflows/update_gdocs_data.yml

It looks like an update to the GH actions runner image recently changed the installed `pip` version to "`>=24.1`".  A dependency we have pinned uses a version spec syntax that is not compatible with this...
<details>
<summary>GH actions output:</summary>
```
...
Collecting dropbox==11.36.0 (from -r requirements.dev.txt (line 6))
Downloading dropbox-11.36.0-py3-none-any.whl.metadata (4.3 kB)
WARNING: Ignoring version 11.36.0 of dropbox since it has invalid metadata:
Requested dropbox==11.36.0 from https://files.pythonhosted.org/packages/11/7e/e66327f3535cf5b58b3c152144744fc5727355357304facf61e43ab1b895/dropbox-11.36.0-py3-none-any.whl (from -r requirements.dev.txt (line 6)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
stone (>=2.*)
~~~~^
Please use pip<24.1 …
```

Troubleshooting & [hackily] fixing GH action for signals sync (gdoc-->csv)

---

integrations/client/test_delphi_epidata.py
src/client/delphi_epidata.py
src/client/packaging/pypi/CHANGELOG.md

fixes on top of #1456, to address CI failures seen in #1496

py client version check fixes and cleanup

---

.github/PULL_REQUEST_TEMPLATE.md

[Certain phrasing in a PR can "link" it to a particular issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).  Merging a PR that is "linked" to an issue will automatically close that issue.  This can be handy, but it can also be problematic if the issue is closed unintentionally, like when a PR does not completely cover all of the points made in the issue.  For examples of this, see: https://github.com/cmu-delphi/covidcast-indicators/issues/1676#issuecomment-2118194957 and https://github.com/cmu-delphi/covidcast-indicators/issues/1973#issuecomment-2249126852 .  The automatic closing behavior can not be disabled, though it is a …

avoid linking keywords in PR template

---

docs/api/covidcast-signals/chng.md

Add inpatient, outpatient signals doc

---

docs/api/covidcast-signals/nssp.md

Minor doc updates corresponding to https://github.com/cmu-delphi/covidcast-indicators/pull/2036
- [NA] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [NA] Build is successful
- [NA] Code is cleaned up and formatted

minor update to nssp docs

---

docs/api/covidcast_licensing.md

addresses issue(s) #ISSUE 
Add missing signals to covidcast license page. Alphabetize.

Update covidcast license page signal list

---

docs/api/covidcast-signals/covid-act-now.md
docs/api/covidcast-signals/dsew-cpr.md
docs/api/covidcast-signals/ght.md
docs/api/covidcast-signals/google-symptoms.md
docs/api/covidcast-signals/hhs.md
docs/api/covidcast-signals/jhu-csse.md
docs/api/covidcast-signals/safegraph.md
docs/api/covidcast-signals/usa-facts.md
docs/api/covidcast-signals/youtube-survey.md

Mark Google Health Trends as inactive. Rename Google symptoms page. Make all headers have the same format (`nav_order` in the same place).

Switch Google Health Trends and Google Symptoms inactive/active marking

---

.github/workflows/missing_signals.yaml
.github/workflows/performance-tests-one-time.yml
.github/workflows/performance-tests.yml
.github/workflows/release-helper.yml

addresses #1540
Changes all `actions/upload-artifact@v2` to `actions/upload-artifact@v4`. There's no use of download-artifact in the repo.

upload-artifact@v2 -> v4

---

docs/api/twitter.md

Added source citation to twitter endpoint.

---

docs/api/covidcast-signals/indicator-combination.md

Move indicator combo "statistical" signals to a table for easier reading, closes #1522

Tina indicator comb sig table

---

docs/api/covidcast-signals/nchs-mortality.md

closes #1519
- [x ] Unless it is a documentation hotfix it should be merged against the `dev` branch
- [x ] Branch is up-to-date with the branch to be merged with, i.e. `dev`

Edited language in NCHS Mortality regarding weekly deaths

---

docs/api/api_keys.md
docs/api/client_libraries.md
docs/api/covidcast.md
docs/api/covidcast_clients.md

Mention `epidatpy` everywhere as a current client. Give `epidatpy` examples. Link to package-specific API key help info.

Mention `epidatpy` everywhere as a current client

---

.github/workflows/performance-tests-one-time.yml
.github/workflows/performance-tests.yml

addresses issue(s) #1556 
Removes the step to install/set up WireGuard from the performance testing Actions workflows.
Reason:
- The WireGuard setup, though pretty stable overall, recently failed in our test environment and resulted in a lot of spurious monitoring alerts. We don't need it anymore because we now run these workflows via local runner that has more direct access to the test environment.
NOTE: There is also an Actions secret used in these workflows of `DB_CONN_STRING` that has already been updated and tested.

Remove WireGuard step

---

tests/server/test_pandas.py

The CI build is currently broken by an import error, but this PR includes a simple fix.
Last successful build:
https://github.com/cmu-delphi/delphi-epidata/actions/runs/12265958980/job/34223121686
Dec 10, 2024
runner image `ubuntu-22.04` version `20241201.1.0`
First failing build:
https://github.com/cmu-delphi/delphi-epidata/actions/runs/12635938712/job/35206910938
Jan 6, 2025
runner image `ubuntu-24.04` version `20241215.1.0`
I'm guessing that these version changes are the cause of the error.  I would have thought that we would be protected from such problems since the tests run inside docker.  (Maybe it does protect us?  Which would then mean that something else is the cause...)
Going from ubuntu 22 to ubuntu 24 is kind of a big step to happen without warning...  Do we want to consider …

fix unittest.mock import error

---

docs/api/covidcast-signals/nssp.md

For context, check [covidcast-indicators repo issue #2099](https://github.com/cmu-delphi/covidcast-indicators/issues/2099)
Remove all mention of secondary source from nssp docs.

Remove mention of secondary signals from NSSP docs

---

docs/api/covidcast-signals/nhsn.md

while we figure out the verbiage for the relationship between data from source `hhs` and source `nhsn` in #1581, this fixes just the text that was inherited from the `nssp` documentation, so we can release it to the public site.

NHSN documentation fixes for page title and heading

---

integrations/acquisition/covidcast/test_coverage_crossref_update.py
src/acquisition/covidcast/database.py
src/ddl/v4_schema.sql
src/ddl/v4_schema_aliases.sql
src/maintenance/coverage_crossref_updater.py
src/server/endpoints/covidcast.py
tests/acquisition/covidcast/test_database.py

addresses issue(s) #1583 
Create a new endpoint that returns a list of signals when given a geo. There were other endpoints that did this in the past, but the tables they read from are no longer around in epi v4. Starting from scratch will be much quicker and rely less on legacy code.
Once this is merged, I will also make issues to delete the old coverage code so that we don't have duplicate endpoints.

Signal Documentation Coverage Endpoint

---

tasks.py

What i was referring to in https://github.com/cmu-delphi/delphi-epidata/pull/1546#issuecomment-2400786489 is not actually a problem with extended ascii or unicode characters -- unicode seems like it should actually be fine to use as long as it is decoded properly...
* In #1546, i saw the replacement of weird ascii characters (that i thought might have been escaped to comply with some CSV format) with what i thought were proper/plain quotation marks (they were actually unicode's stylized quotes).  
* `db_signals.csv` in the current `main` branch has the weird extended ascii chars (Search for "Children cannot get COVID-19" to see an example: https://github.com/cmu-delphi/delphi-epidata/blob/9e21bfb8c4698d114d3b5cc7b5ad534cddebefdf/src/server/endpoints/covidcast_utils/db_signals.csv#L139 ). …

Properly decode UTF-8 from gsheet csv

---

docs/symptom-survey/collaboration-revision.md
docs/symptom-survey/contingency-tables.md
docs/symptom-survey/data-access.md
docs/symptom-survey/end-of-survey.md
docs/symptom-survey/index.md
docs/symptom-survey/server-access.md
docs/symptom-survey/survey-files.md

Now that the CTIS data is [archived with ICPSR](https://www.icpsr.umich.edu/web/ICPSR/studies/39207), we can point there and deprecate pages describing access to microdata via CMU. ICPSR also archives the contingency tables, including a user guide, so we can remove the redundant contingency table documentation and point to ICPSR instead.

Update CTIS documentation to point to ICPSR

---

docs/symptom-survey/index.md

It doesn't get rewritten to link to the .html page if it's split across lines. I forgot about this annoying bug while making the previous PR.

Fix link to data access page

---

docs/api/covidcast-signals/nssp.md

* Closes #1631
Released changes will appear on our `github.io` API documentation site:
https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/nssp.html
Original source "about" page:
https://data.cdc.gov/Public-Health-Surveillance/NSSP-Emergency-Department-Visit-Trajectories-by-St/rdmq-nq56/about_data

Clarify NSSP documentation, especially 'HSA' semantics

---

docs/api/covidcast-signals/nssp.md

Text suggested by @RoniRos to clarify [the somewhat clunky existing description in the github.io documentation](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/nssp.html#:~:text=county%2C%20state,have%20identical%20values).

clarify relationship of nssp data on counties and HSAs

---

dev/docker/python/Dockerfile
integrations/server/test_covidcast_endpoints.py
src/server/endpoints/covidcast.py

Added new /indicator_geo_coverage endpoint.
It accepts source:signals and returns list of available geo_type:geo_value pairs.
This endpoint is needed for the EpiPortal to show the only list of available geos for the selected indicators.

/indicator_geo_coverage endpoint
